import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const output = resolve('src/generated/openTdbGameShow.ts');
const target = Number(process.argv[2] ?? 250);
const batchSize = 50;
const delayMs = 5200;

const categoryTopic = new Map([
  ['General Knowledge', 'history'],
  ['Entertainment: Books', 'arts'],
  ['Entertainment: Film', 'cinema'],
  ['Entertainment: Music', 'arts'],
  ['Entertainment: Musicals & Theatres', 'arts'],
  ['Entertainment: Television', 'cinema'],
  ['Entertainment: Video Games', 'technology'],
  ['Entertainment: Board Games', 'sport'],
  ['Science & Nature', 'science'],
  ['Science: Computers', 'technology'],
  ['Science: Mathematics', 'science'],
  ['Mythology', 'history'],
  ['Sports', 'sport'],
  ['Geography', 'geography'],
  ['History', 'history'],
  ['Politics', 'economy'],
  ['Art', 'arts'],
  ['Celebrities', 'cinema'],
  ['Animals', 'nature'],
  ['Vehicles', 'technology'],
  ['Entertainment: Comics', 'arts'],
  ['Science: Gadgets', 'technology'],
  ['Entertainment: Japanese Anime & Manga', 'arts'],
  ['Entertainment: Cartoon & Animations', 'arts'],
]);

function wait(ms) {
  return new Promise((resolveWait) => setTimeout(resolveWait, ms));
}

async function fetchJson(url) {
  const response = await fetch(url, { headers: { 'User-Agent': 'Kizz/0.1 educational importer' } });
  if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
  return response.json();
}

function decode(value) {
  try { return decodeURIComponent(value); } catch { return value; }
}

function normalizeWhitespace(value) {
  return value.replace(/\s+/g, ' ').trim();
}

function hashText(value) {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) hash = ((hash << 5) - hash + value.charCodeAt(index)) | 0;
  return Math.abs(hash);
}

function rotateChoices(choices, prompt) {
  const offset = hashText(prompt) % choices.length;
  return [...choices.slice(offset), ...choices.slice(0, offset)];
}

function difficultyToNumber(difficulty) {
  if (difficulty === 'easy') return 1;
  if (difficulty === 'medium') return 2;
  return 3;
}

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 18) || 'trivia';
}

const tokenPayload = await fetchJson('https://opentdb.com/api_token.php?command=request');
if (tokenPayload.response_code !== 0) throw new Error(`OpenTDB token error ${tokenPayload.response_code}`);
const token = tokenPayload.token;

const seenPrompts = new Set();
const imported = [];
let call = 0;

while (imported.length < target) {
  if (call > 0) await wait(delayMs);
  call += 1;
  const amount = Math.min(batchSize, target - imported.length);
  const url = `https://opentdb.com/api.php?amount=${amount}&type=multiple&encode=url3986&token=${encodeURIComponent(token)}`;
  const payload = await fetchJson(url);
  if (payload.response_code === 4) break;
  if (payload.response_code === 5) {
    await wait(delayMs * 2);
    call -= 1;
    continue;
  }
  if (payload.response_code !== 0) throw new Error(`OpenTDB API response_code ${payload.response_code}`);

  for (const item of payload.results) {
    const prompt = normalizeWhitespace(decode(item.question));
    if (!prompt || seenPrompts.has(prompt)) continue;
    seenPrompts.add(prompt);

    const correct = normalizeWhitespace(decode(item.correct_answer));
    const incorrect = item.incorrect_answers.map((answer) => normalizeWhitespace(decode(answer)));
    const choices = rotateChoices([correct, ...incorrect], prompt);
    const answerIndex = choices.indexOf(correct);
    const topicId = categoryTopic.get(decode(item.category)) ?? 'history';
    const sourceCategory = decode(item.category);
    imported.push({
      id: `otdb-${String(imported.length + 1).padStart(4, '0')}-${slug(sourceCategory)}`,
      topicId,
      difficulty: difficultyToNumber(item.difficulty),
      prompt,
      choices,
      answerIndex,
      explanation: `${correct} est la bonne réponse. Question issue d'une banque de trivia ouverte, proche du format jeu télé: réponse courte, quatre propositions, correction immédiate.`,
      tags: ['open-trivia-db', 'jeu-tele', slug(sourceCategory), item.difficulty],
      sourceLabel: 'Open Trivia DB — CC BY-SA 4.0',
      sourceUrl: 'https://opentdb.com/',
      learnMoreUrl: `https://fr.wikipedia.org/w/index.php?search=${encodeURIComponent(correct)}`,
    });
    if (imported.length >= target) break;
  }
}

const moduleSource = `// Generated by scripts/import-opentdb.mjs. Do not edit manually.
import { QuestionSeed } from '../domain';

export const openTdbGameShowQuestions: QuestionSeed[] = ${JSON.stringify(imported, null, 2)};
`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, moduleSource, 'utf8');
console.log(`Generated ${imported.length} questions in ${output}`);
