import { QuestionSeed } from './domain';

const sourceLabel = 'Contenu original Kizz (inspiré de formats de quiz populaires)';

const rawGameStyleQuestions: QuestionSeed[] = [
  {
    id: 'style-ttmc-001',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Format TTMC niveau 2 : quelle mer borde Marseille ?',
    choices: ['Mer Noire', 'Mer Baltique', 'Méditerranée', 'Mer du Nord'],
    answerIndex: 2,
    explanation: 'Marseille est une ville portuaire de la côte méditerranéenne française.',
    tags: ['style:ttmc', 'geography', 'france'],
    sourceLabel,
  },
  {
    id: 'style-ttmc-002',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Format TTMC niveau 4 : quel pays est situé entre la France et l’Espagne ?',
    choices: ['Andorre', 'Portugal', 'Monaco', 'Suisse'],
    answerIndex: 0,
    explanation: 'Andorre est un micro-État des Pyrénées, entre la France et l’Espagne.',
    tags: ['style:ttmc', 'placement-pays', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-ttmc-003',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Format TTMC niveau 5 : quelle est la capitale de la Norvège ?',
    choices: ['Stockholm', 'Helsinki', 'Oslo', 'Reykjavik'],
    answerIndex: 2,
    explanation: 'Oslo est la capitale de la Norvège.',
    tags: ['style:ttmc', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-ttmc-004',
    topicId: 'history',
    difficulty: 3,
    prompt: 'Format TTMC niveau 7 : en quelle année tombe le mur de Berlin ?',
    choices: ['1987', '1988', '1989', '1991'],
    answerIndex: 2,
    explanation: 'Le mur de Berlin tombe en novembre 1989.',
    tags: ['style:ttmc', 'history', 'europe'],
    sourceLabel,
  },
  {
    id: 'style-trivial-001',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Style Trivial Poursuite : quelle est la capitale du Canada ?',
    choices: ['Toronto', 'Ottawa', 'Montréal', 'Québec'],
    answerIndex: 1,
    explanation: 'Ottawa est la capitale fédérale du Canada.',
    tags: ['style:trivial-poursuite', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-trivial-002',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Style Trivial Poursuite : quel pays a pour capitale Lima ?',
    choices: ['Bolivie', 'Chili', 'Pérou', 'Équateur'],
    answerIndex: 2,
    explanation: 'Lima est la capitale du Pérou.',
    tags: ['style:trivial-poursuite', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-trivial-003',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Style Trivial Poursuite : quel pays est au sud du Canada ?',
    choices: ['Mexique', 'États-Unis', 'Groenland', 'Cuba'],
    answerIndex: 1,
    explanation: 'Les États-Unis partagent une très longue frontière avec le Canada.',
    tags: ['style:trivial-poursuite', 'placement-pays', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-trivial-004',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Style Trivial Poursuite : quel est le plus grand océan du monde ?',
    choices: ['Atlantique', 'Pacifique', 'Indien', 'Arctique'],
    answerIndex: 1,
    explanation: 'Le Pacifique est l’océan le plus vaste.',
    tags: ['style:trivial-poursuite', 'oceans', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-jeutv-001',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Style jeu télé, réponse rapide : capitale du Japon ?',
    choices: ['Kyoto', 'Tokyo', 'Osaka', 'Nagoya'],
    answerIndex: 1,
    explanation: 'Tokyo est la capitale du Japon.',
    tags: ['style:jeu-tele', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-jeutv-002',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Style jeu télé : quel pays est traversé par le Nil et a Le Caire pour capitale ?',
    choices: ['Maroc', 'Égypte', 'Soudan', 'Tunisie'],
    answerIndex: 1,
    explanation: 'Le Caire est la capitale de l’Égypte.',
    tags: ['style:jeu-tele', 'capitales', 'afrique'],
    sourceLabel,
  },
  {
    id: 'style-jeutv-003',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Style jeu télé : quel pays est situé entre l’Espagne et la France ?',
    choices: ['Andorre', 'Italie', 'Luxembourg', 'Belgique'],
    answerIndex: 0,
    explanation: 'Andorre se situe dans les Pyrénées, entre les deux pays.',
    tags: ['style:jeu-tele', 'placement-pays', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-jeutv-004',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Style jeu télé : quelle capitale a été divisée par un mur jusqu’en 1989 ?',
    choices: ['Prague', 'Varsovie', 'Berlin', 'Vienne'],
    answerIndex: 2,
    explanation: 'Berlin fut divisée entre Est et Ouest durant la guerre froide.',
    tags: ['style:jeu-tele', 'history', 'capitales'],
    sourceLabel,
  },
  {
    id: 'style-qpc-001',
    topicId: 'geography',
    difficulty: 1,
    type: 'free-text',
    prompt: 'Question pour un champion : capitale de l’Italie ?',
    acceptedAnswers: ['rome'],
    explanation: 'Rome est la capitale de l’Italie.',
    tags: ['style:question-pour-un-champion', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-qpc-002',
    topicId: 'geography',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Question pour un champion : je suis la capitale du Portugal. Qui suis-je ?',
    acceptedAnswers: ['lisbonne', 'lisboa'],
    explanation: 'Lisbonne est la capitale du Portugal.',
    tags: ['style:question-pour-un-champion', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-qpc-003',
    topicId: 'geography',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Question pour un champion : pays frontalier de la France au sud-ouest ?',
    acceptedAnswers: ['espagne', "l'espagne"],
    explanation: 'La France partage sa frontière sud-ouest avec l’Espagne.',
    tags: ['style:question-pour-un-champion', 'placement-pays', 'geography', 'france'],
    sourceLabel,
  },
  {
    id: 'style-qpc-004',
    topicId: 'geography',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Question pour un champion : capitale de l’Argentine ?',
    acceptedAnswers: ['buenos aires'],
    explanation: 'Buenos Aires est la capitale de l’Argentine.',
    tags: ['style:question-pour-un-champion', 'capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-cap-001',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Pays & capitales : quelle est la capitale de l’Espagne ?',
    choices: ['Barcelone', 'Madrid', 'Valence', 'Séville'],
    answerIndex: 1,
    explanation: 'Madrid est la capitale de l’Espagne.',
    tags: ['capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-cap-002',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Pays & capitales : quelle est la capitale de l’Allemagne ?',
    choices: ['Munich', 'Hambourg', 'Berlin', 'Cologne'],
    answerIndex: 2,
    explanation: 'Berlin est la capitale allemande.',
    tags: ['capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-cap-003',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Placement de pays : lequel est à l’est de la France ?',
    choices: ['Portugal', 'Irlande', 'Allemagne', 'Islande'],
    answerIndex: 2,
    explanation: 'L’Allemagne est à l’est de la France.',
    tags: ['placement-pays', 'geography', 'france'],
    sourceLabel,
  },
  {
    id: 'style-cap-004',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Placement de pays : lequel est au nord de l’Italie ?',
    choices: ['Grèce', 'Autriche', 'Malte', 'Tunisie'],
    answerIndex: 1,
    explanation: 'L’Autriche est située au nord de l’Italie.',
    tags: ['placement-pays', 'geography', 'europe'],
    sourceLabel,
  },
  {
    id: 'style-cap-005',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Pays & capitales : quelle est la capitale du Kenya ?',
    choices: ['Mombasa', 'Kampala', 'Nairobi', 'Addis-Abeba'],
    answerIndex: 2,
    explanation: 'Nairobi est la capitale du Kenya.',
    tags: ['capitales', 'geography', 'afrique'],
    sourceLabel,
  },
  {
    id: 'style-cap-006',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Pays & capitales : quelle est la capitale de la Turquie ?',
    choices: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
    answerIndex: 1,
    explanation: 'Ankara est la capitale de la Turquie.',
    tags: ['capitales', 'geography'],
    sourceLabel,
  },
  {
    id: 'style-cap-007',
    topicId: 'geography',
    difficulty: 3,
    prompt: 'Placement de pays : lequel est enclavé entre la France, la Belgique et l’Allemagne ?',
    choices: ['Suisse', 'Luxembourg', 'Liechtenstein', 'Autriche'],
    answerIndex: 1,
    explanation: 'Le Luxembourg est frontalier de la France, de la Belgique et de l’Allemagne.',
    tags: ['placement-pays', 'geography', 'europe'],
    sourceLabel,
  },
  {
    id: 'style-cap-008',
    topicId: 'geography',
    difficulty: 2,
    prompt: 'Pays & capitales : quelle est la capitale de la Nouvelle-Zélande ?',
    choices: ['Auckland', 'Christchurch', 'Wellington', 'Dunedin'],
    answerIndex: 2,
    explanation: 'Wellington est la capitale de la Nouvelle-Zélande.',
    tags: ['capitales', 'geography', 'oceanie'],
    sourceLabel,
  },
];

export const gameStyleQuestions: QuestionSeed[] = rawGameStyleQuestions.map((question) => ({
  ...question,
  explanation: question.explanation.length < 38 ? `${question.explanation} Ce repere reste volontairement court pour un format de reponse rapide.` : question.explanation,
}));
