import { QuestionSeed } from './domain';

export const subthemeExpansionQuestions: QuestionSeed[] = [
  {
    id: 'sub-history-prehistory-001',
    topicId: 'history',
    difficulty: 1,
    prompt: 'Prehistoire : quelle innovation transforme durablement la vie humaine au Neolithique ?',
    choices: ['La metallurgie industrielle', 'L agriculture', 'L imprimerie', 'La machine a vapeur'],
    answerIndex: 1,
    explanation: 'Le Neolithique marque la sedentarisation progressive, avec agriculture et elevage.',
    tags: ['histoire', 'prehistoire', 'neolithique', 'subtheme:history:prehistory'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-medieval-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Moyen Age : quel empire est couronne avec Charlemagne en 800 ?',
    choices: ['Empire carolingien', 'Empire ottoman', 'Empire inca', 'Empire moghol'],
    answerIndex: 0,
    explanation: 'Charlemagne est couronne empereur a Rome en 800, au coeur de l empire carolingien.',
    tags: ['histoire', 'moyen-age', 'france', 'subtheme:history:medieval'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-italy-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Histoire italienne : quel mouvement politique aboutit a l unification de l Italie au XIXe siecle ?',
    choices: ['Risorgimento', 'Restauration Meiji', 'Reconquista', 'Perestroika'],
    answerIndex: 0,
    explanation: 'Le Risorgimento designe le processus d unification politique de l Italie.',
    tags: ['histoire', 'italie', 'xixe-siecle', 'subtheme:history:italy'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-germany-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Histoire allemande : quel evenement de 1989 symbolise la fin de la division de Berlin ?',
    choices: ['La chute du mur de Berlin', 'Le traite de Verdun', 'La bataille de Leipzig', 'Le congres de Vienne'],
    answerIndex: 0,
    explanation: 'La chute du mur de Berlin, le 9 novembre 1989, ouvre la voie a la reunification allemande.',
    tags: ['histoire', 'allemagne', 'xxe-siecle', 'subtheme:history:germany', 'subtheme:history:contemporary'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-science-chemistry-001',
    topicId: 'science',
    difficulty: 1,
    prompt: 'Chimie : quel symbole designe l oxygene dans le tableau periodique ?',
    choices: ['O', 'Ox', 'Og', 'Oy'],
    answerIndex: 0,
    explanation: 'Le symbole chimique de l oxygene est O.',
    tags: ['science', 'chimie', 'subtheme:science:chemistry'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-science-earth-001',
    topicId: 'science',
    difficulty: 2,
    prompt: 'Sciences de la Terre : comment appelle-t-on la couche externe rigide de la Terre ?',
    choices: ['Lithosphere', 'Troposphere', 'Chromosphere', 'Hydrosphere'],
    answerIndex: 0,
    explanation: 'La lithosphere regroupe la croute et la partie superieure rigide du manteau.',
    tags: ['science', 'terre', 'geologie', 'subtheme:science:earth'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-sport-team-001',
    topicId: 'sport',
    difficulty: 1,
    prompt: 'Sport collectif : dans quel sport joue-t-on traditionnellement a cinq contre cinq ?',
    choices: ['Basket-ball', 'Rugby a XV', 'Baseball', 'Volley-ball de plage'],
    answerIndex: 0,
    explanation: 'Le basket-ball oppose deux equipes de cinq joueurs sur le terrain.',
    tags: ['sport', 'basket-ball', 'subtheme:sport:team'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-arts-museum-001',
    topicId: 'arts',
    difficulty: 1,
    prompt: 'Musees : dans quelle ville se trouve le musee d Orsay ?',
    choices: ['Paris', 'Lyon', 'Marseille', 'Nantes'],
    answerIndex: 0,
    explanation: 'Le musee d Orsay se trouve a Paris, dans une ancienne gare.',
    tags: ['arts', 'musee', 'subtheme:arts:museums'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-cinema-movement-001',
    topicId: 'cinema',
    difficulty: 2,
    prompt: 'Cinema : quel mouvement francais est associe a Truffaut et Godard ?',
    choices: ['Nouvelle Vague', 'Dogme 95', 'Neo-realisme', 'Expressionnisme allemand'],
    answerIndex: 0,
    explanation: 'La Nouvelle Vague renouvelle le cinema francais a partir de la fin des annees 1950.',
    tags: ['cinema', 'mouvement', 'subtheme:cinema:movements'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-architecture-vocabulary-001',
    topicId: 'architecture',
    difficulty: 1,
    prompt: 'Architecture : comment appelle-t-on l espace central d une eglise entre l entree et le choeur ?',
    choices: ['La nef', 'Le parvis', 'La fleche', 'Le contrefort'],
    answerIndex: 0,
    explanation: 'La nef est l espace principal ou se rassemblent les fideles.',
    tags: ['architecture', 'vocabulaire', 'subtheme:architecture:vocabulary'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-economy-finance-001',
    topicId: 'economy',
    difficulty: 2,
    prompt: 'Finance : comment appelle-t-on un emprunt emis par un Etat ou une entreprise ?',
    choices: ['Une obligation', 'Une facture', 'Un dividende', 'Une franchise'],
    answerIndex: 0,
    explanation: 'Une obligation est un titre de dette qui correspond a un emprunt.',
    tags: ['economie', 'finance', 'subtheme:economy:finance'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-nature-plants-001',
    topicId: 'nature',
    difficulty: 1,
    prompt: 'Plantes : quelle partie contient souvent les graines chez une plante a fleurs ?',
    choices: ['Le fruit', 'La racine', 'La tige', 'Le pollen'],
    answerIndex: 0,
    explanation: 'Le fruit protege et aide souvent a disperser les graines.',
    tags: ['nature', 'botanique', 'subtheme:nature:plants'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-technology-software-001',
    topicId: 'technology',
    difficulty: 2,
    prompt: 'Logiciel : quel terme designe une interface qui permet a deux programmes de communiquer ?',
    choices: ['API', 'OLED', 'SSD', 'NFC'],
    answerIndex: 0,
    explanation: 'Une API expose des fonctions ou donnees pour qu un autre logiciel les utilise.',
    tags: ['technologie', 'logiciel', 'api', 'subtheme:technology:software'],
    sourceLabel: 'Contenu original Kizz',
  },
];
