import { QuestionSeed } from './domain';

const commons = {
  'starry-night': 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
  'girl-pearl-earring': 'https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_(1632-1675)_-_The_Girl_With_The_Pearl_Earring_(1665).jpg',
  'birth-venus': 'https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_046.jpg',
  'liberty-leading': 'https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg',
  'great-wave': 'https://commons.wikimedia.org/wiki/File:The_Great_Wave_off_Kanagawa.jpg',
  'venus-milo': 'https://commons.wikimedia.org/wiki/File:Venus_de_Milo.JPG',
  'david-michelangelo': 'https://commons.wikimedia.org/wiki/File:Statue_of_David_by_Michelangelo_(15609869928).jpg',
  'winged-victory': 'https://commons.wikimedia.org/wiki/File:Wing_victory_Samothrace_Louvre_Ma2369.jpg',
  'notre-dame-paris': 'https://commons.wikimedia.org/wiki/File:Notre_Dame_Paris_front_facade_lower.jpg',
  colosseum: 'https://commons.wikimedia.org/wiki/File:Rome_Colosseum_exterior_1.jpg',
  parthenon: 'https://commons.wikimedia.org/wiki/File:Parthenon_from_south.jpg',
  'sagrada-familia': 'https://commons.wikimedia.org/wiki/File:Barcelona_-_Exterior_of_the_Apse_of_the_Sagrada_Fam%C3%ADlia_-_Western_exposure.jpg',
  'eiffel-tower': 'https://commons.wikimedia.org/wiki/File:EiffelTowerdayshootbyedwintan.jpg',
  'villa-savoye': 'https://commons.wikimedia.org/wiki/File:Savoye_3.JPG',
};

const artworkChoices: [string, string, string, string] = ['La Nuit étoilée', 'La Jeune Fille à la perle', 'La Naissance de Vénus', 'La Liberté guidant le peuple'];
const artworkAssets: [string, string, string, string] = ['starry-night', 'girl-pearl-earring', 'birth-venus', 'liberty-leading'];
const artworkAlts: [string, string, string, string] = ['La Nuit étoilée', 'La Jeune Fille à la perle', 'La Naissance de Vénus', 'La Liberté guidant le peuple'];

const buildingChoices: [string, string, string, string] = ['Notre-Dame de Paris', 'Le Colisée', 'Le Parthénon', 'La Sagrada Família'];
const buildingAssets: [string, string, string, string] = ['notre-dame-paris', 'colosseum', 'parthenon', 'sagrada-familia'];
const buildingAlts: [string, string, string, string] = ['Façade de Notre-Dame de Paris', 'Extérieur du Colisée', 'Le Parthénon à Athènes', 'Extérieur de la Sagrada Família'];

export const visualRecognitionQuestions: QuestionSeed[] = [
  {
    id: 'visual-art-001',
    topicId: 'arts',
    difficulty: 1,
    prompt: 'Quel est le nom de ce tableau ?',
    choices: ['La Nuit étoilée', 'Guernica', 'Le Cri', 'Impression, soleil levant'],
    answerIndex: 0,
    explanation: 'La Nuit étoilée est peinte par Vincent van Gogh en 1889.',
    tags: ['arts', 'peinture', 'image', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['starry-night'],
    imageAsset: 'starry-night',
    imageAlt: 'La Nuit étoilée de Vincent van Gogh',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/La_Nuit_%C3%A9toil%C3%A9e',
  },
  {
    id: 'visual-art-002',
    topicId: 'arts',
    difficulty: 1,
    prompt: 'Qui a peint cette oeuvre ?',
    choices: ['Johannes Vermeer', 'Rembrandt', 'Diego Velázquez', 'Jan van Eyck'],
    answerIndex: 0,
    explanation: 'La Jeune Fille à la perle est attribuée à Johannes Vermeer.',
    tags: ['arts', 'peinture', 'image', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['girl-pearl-earring'],
    imageAsset: 'girl-pearl-earring',
    imageAlt: 'La Jeune Fille à la perle',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/La_Jeune_Fille_%C3%A0_la_perle',
  },
  {
    id: 'visual-art-003',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Quel tableau est représenté ici ?',
    choices: ['La Naissance de Vénus', 'Le Printemps', 'La Vénus d’Urbino', 'Les Trois Grâces'],
    answerIndex: 0,
    explanation: 'La Naissance de Vénus est une oeuvre majeure de Sandro Botticelli.',
    tags: ['arts', 'peinture', 'renaissance', 'image', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['birth-venus'],
    imageAsset: 'birth-venus',
    imageAlt: 'La Naissance de Vénus de Botticelli',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/La_Naissance_de_V%C3%A9nus',
  },
  {
    id: 'visual-art-004',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Qui a peint La Liberté guidant le peuple ?',
    choices: ['Eugène Delacroix', 'Théodore Géricault', 'Jacques-Louis David', 'Gustave Courbet'],
    answerIndex: 0,
    explanation: 'Eugène Delacroix peint cette scène allégorique après la révolution de Juillet 1830.',
    tags: ['arts', 'peinture', 'romantisme', 'image', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['liberty-leading'],
    imageAsset: 'liberty-leading',
    imageAlt: 'La Liberté guidant le peuple',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/La_Libert%C3%A9_guidant_le_peuple',
  },
  {
    id: 'visual-art-005',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Quel artiste japonais a créé cette estampe ?',
    choices: ['Hokusai', 'Hiroshige', 'Utamaro', 'Kuniyoshi'],
    answerIndex: 0,
    explanation: 'La Grande Vague de Kanagawa est une estampe de Katsushika Hokusai.',
    tags: ['arts', 'estampe', 'japon', 'image', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['great-wave'],
    imageAsset: 'great-wave',
    imageAlt: 'La Grande Vague de Kanagawa',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/La_Grande_Vague_de_Kanagawa',
  },
  {
    id: 'visual-art-006',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Sélectionne l’image de La Jeune Fille à la perle.',
    choices: [...artworkChoices],
    choiceImageAssets: [...artworkAssets],
    choiceImageAlts: [...artworkAlts],
    answerIndex: 1,
    explanation: 'La Jeune Fille à la perle se reconnaît à son fond sombre, son turban et sa perle lumineuse.',
    tags: ['arts', 'peinture', 'image-choice', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - images domaine public',
    sourceUrl: commons['girl-pearl-earring'],
  },
  {
    id: 'visual-art-007',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Sélectionne l’image de La Grande Vague de Kanagawa.',
    choices: ['La Grande Vague', 'La Nuit étoilée', 'La Naissance de Vénus', 'La Liberté guidant le peuple'],
    choiceImageAssets: ['great-wave', 'starry-night', 'birth-venus', 'liberty-leading'],
    choiceImageAlts: ['La Grande Vague de Kanagawa', 'La Nuit étoilée', 'La Naissance de Vénus', 'La Liberté guidant le peuple'],
    answerIndex: 0,
    explanation: 'La Grande Vague est une estampe japonaise dominée par une vague stylisée au premier plan.',
    tags: ['arts', 'estampe', 'image-choice', 'subtheme:arts:painting'],
    sourceLabel: 'Wikimedia Commons - images domaine public',
    sourceUrl: commons['great-wave'],
  },
  {
    id: 'visual-sculpture-001',
    topicId: 'arts',
    difficulty: 1,
    prompt: 'Quelle sculpture voit-on ici ?',
    choices: ['La Vénus de Milo', 'Le Discobole', 'La Pietà', 'Le Baiser'],
    answerIndex: 0,
    explanation: 'La Vénus de Milo est une sculpture antique conservée au musée du Louvre.',
    tags: ['arts', 'sculpture', 'image', 'subtheme:arts:sculpture'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 2.5',
    sourceUrl: commons['venus-milo'],
    imageAsset: 'venus-milo',
    imageAlt: 'La Vénus de Milo',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/V%C3%A9nus_de_Milo',
  },
  {
    id: 'visual-sculpture-002',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Quel artiste a sculpté le David montré ici ?',
    choices: ['Michel-Ange', 'Donatello', 'Bernin', 'Canova'],
    answerIndex: 0,
    explanation: 'Le David de Michel-Ange est l’un des emblèmes de la sculpture de la Renaissance.',
    tags: ['arts', 'sculpture', 'renaissance', 'image', 'subtheme:arts:sculpture'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 2.0',
    sourceUrl: commons['david-michelangelo'],
    imageAsset: 'david-michelangelo',
    imageAlt: 'David de Michel-Ange',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/David_(Michel-Ange)',
  },
  {
    id: 'visual-sculpture-003',
    topicId: 'arts',
    difficulty: 2,
    prompt: 'Quel est le nom de cette sculpture antique ?',
    choices: ['Victoire de Samothrace', 'Vénus de Milo', 'Laocoon', 'Niké d’Athènes'],
    answerIndex: 0,
    explanation: 'La Victoire de Samothrace représente la déesse Niké et se trouve au Louvre.',
    tags: ['arts', 'sculpture', 'antiquité', 'image', 'subtheme:arts:sculpture'],
    sourceLabel: 'Wikimedia Commons - domaine public',
    sourceUrl: commons['winged-victory'],
    imageAsset: 'winged-victory',
    imageAlt: 'Victoire de Samothrace',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Victoire_de_Samothrace',
  },
  {
    id: 'visual-arch-001',
    topicId: 'architecture',
    difficulty: 1,
    prompt: 'Quel bâtiment reconnais-tu sur cette image ?',
    choices: ['Notre-Dame de Paris', 'La cathédrale de Chartres', 'Le Panthéon', 'Le Sacré-Coeur'],
    answerIndex: 0,
    explanation: 'La façade à deux tours est l’un des repères visuels de Notre-Dame de Paris.',
    tags: ['architecture', 'édifice', 'france', 'image', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 3.0',
    sourceUrl: commons['notre-dame-paris'],
    imageAsset: 'notre-dame-paris',
    imageAlt: 'Façade de Notre-Dame de Paris',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Cath%C3%A9drale_Notre-Dame_de_Paris',
  },
  {
    id: 'visual-arch-002',
    topicId: 'architecture',
    difficulty: 1,
    prompt: 'Quel monument antique est visible ici ?',
    choices: ['Le Colisée', 'Le Panthéon de Rome', 'Le Circus Maximus', 'Les thermes de Caracalla'],
    answerIndex: 0,
    explanation: 'Le Colisée est un amphithéâtre romain célèbre pour ses arcades superposées.',
    tags: ['architecture', 'édifice', 'rome', 'image', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 4.0',
    sourceUrl: commons.colosseum,
    imageAsset: 'colosseum',
    imageAlt: 'Extérieur du Colisée',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Colis%C3%A9e',
  },
  {
    id: 'visual-arch-003',
    topicId: 'architecture',
    difficulty: 2,
    prompt: 'Quel édifice grec est représenté ?',
    choices: ['Le Parthénon', 'Le temple de Zeus à Olympie', 'Le théâtre d’Épidaure', 'Le palais de Cnossos'],
    answerIndex: 0,
    explanation: 'Le Parthénon domine l’Acropole d’Athènes et illustre l’ordre dorique.',
    tags: ['architecture', 'édifice', 'grèce', 'image', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 2.5',
    sourceUrl: commons.parthenon,
    imageAsset: 'parthenon',
    imageAlt: 'Le Parthénon à Athènes',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Parth%C3%A9non',
  },
  {
    id: 'visual-arch-004',
    topicId: 'architecture',
    difficulty: 2,
    prompt: 'Quel architecte est associé à ce bâtiment ?',
    choices: ['Antoni Gaudí', 'Le Corbusier', 'Santiago Calatrava', 'Frank Gehry'],
    answerIndex: 0,
    explanation: 'La Sagrada Família est l’oeuvre la plus célèbre d’Antoni Gaudí à Barcelone.',
    tags: ['architecture', 'édifice', 'gaudí', 'image', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 4.0',
    sourceUrl: commons['sagrada-familia'],
    imageAsset: 'sagrada-familia',
    imageAlt: 'Extérieur de la Sagrada Família',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia',
  },
  {
    id: 'visual-arch-005',
    topicId: 'architecture',
    difficulty: 1,
    prompt: 'Sélectionne l’image du Colisée.',
    choices: [...buildingChoices],
    choiceImageAssets: [...buildingAssets],
    choiceImageAlts: [...buildingAlts],
    answerIndex: 1,
    explanation: 'Le Colisée se reconnaît à sa forme elliptique et à ses niveaux d’arcades.',
    tags: ['architecture', 'image-choice', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - images CC',
    sourceUrl: commons.colosseum,
  },
  {
    id: 'visual-arch-006',
    topicId: 'architecture',
    difficulty: 2,
    prompt: 'Sélectionne l’image de la Sagrada Família.',
    choices: [...buildingChoices],
    choiceImageAssets: [...buildingAssets],
    choiceImageAlts: [...buildingAlts],
    answerIndex: 3,
    explanation: 'La Sagrada Família se distingue par ses tours organiques et sa façade très sculptée.',
    tags: ['architecture', 'image-choice', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - images CC',
    sourceUrl: commons['sagrada-familia'],
  },
  {
    id: 'visual-arch-007',
    topicId: 'architecture',
    difficulty: 2,
    prompt: 'Quel bâtiment moderniste est représenté ici ?',
    choices: ['Villa Savoye', 'Fallingwater', 'Maison Schröder', 'Villa Tugendhat'],
    answerIndex: 0,
    explanation: 'La villa Savoye de Le Corbusier illustre les cinq points de l’architecture moderne.',
    tags: ['architecture', 'modernisme', 'image', 'subtheme:architecture:buildings'],
    sourceLabel: 'Wikimedia Commons - CC0',
    sourceUrl: commons['villa-savoye'],
    imageAsset: 'villa-savoye',
    imageAlt: 'Villa Savoye à Poissy',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Villa_Savoye',
  },
  {
    id: 'visual-geo-001',
    topicId: 'geography',
    difficulty: 1,
    prompt: 'Quel monument parisien reconnais-tu ?',
    choices: ['La tour Eiffel', 'L’Arc de triomphe', 'Le Louvre', 'Notre-Dame'],
    answerIndex: 0,
    explanation: 'La tour Eiffel est un repère majeur de Paris, construite pour l’Exposition universelle de 1889.',
    tags: ['géographie', 'monument', 'france', 'image', 'subtheme:geo:qcm'],
    sourceLabel: 'Wikimedia Commons - CC BY-SA 3.0',
    sourceUrl: commons['eiffel-tower'],
    imageAsset: 'eiffel-tower',
    imageAlt: 'Tour Eiffel de jour',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Tour_Eiffel',
  },
];
