import { QuestionSeed } from './domain';

export const subthemeExpansionQuestions: QuestionSeed[] = [
  {
    id: 'sub-history-prehistory-001',
    topicId: 'history',
    difficulty: 1,
    prompt: 'Préhistoire : quelle innovation transforme durablement la vie humaine au Néolithique ?',
    choices: ['La métallurgie industrielle', 'L’agriculture', 'L’imprimerie', 'La machine à vapeur'],
    answerIndex: 1,
    explanation: 'Le Néolithique marque la sédentarisation progressive, avec agriculture et élevage.',
    tags: ['histoire', 'prehistoire', 'neolithique', 'subtheme:history:prehistory'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-medieval-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Moyen Âge : quel empire est couronné avec Charlemagne en 800 ?',
    choices: ['Empire carolingien', 'Empire ottoman', 'Empire inca', 'Empire moghol'],
    answerIndex: 0,
    explanation: 'Charlemagne est couronné empereur à Rome en 800, au cœur de l’empire carolingien.',
    tags: ['histoire', 'moyen-age', 'france', 'subtheme:history:medieval'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-italy-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Histoire italienne : quel mouvement politique aboutit à l’unification de l’Italie au XIXe siècle ?',
    choices: ['Risorgimento', 'Restauration Meiji', 'Reconquista', 'Perestroika'],
    answerIndex: 0,
    explanation: 'Le Risorgimento désigne le processus d’unification politique de l’Italie.',
    tags: ['histoire', 'italie', 'xixe-siecle', 'subtheme:history:italy'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-history-germany-001',
    topicId: 'history',
    difficulty: 2,
    prompt: 'Histoire allemande : quel événement de 1989 symbolise la fin de la division de Berlin ?',
    choices: ['La chute du mur de Berlin', 'Le traité de Verdun', 'La bataille de Leipzig', 'Le congrès de Vienne'],
    answerIndex: 0,
    explanation: 'La chute du mur de Berlin, le 9 novembre 1989, ouvre la voie à la réunification allemande.',
    tags: ['histoire', 'allemagne', 'xxe-siecle', 'subtheme:history:germany', 'subtheme:history:contemporary'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-science-chemistry-001',
    topicId: 'science',
    difficulty: 1,
    prompt: 'Chimie : quel symbole désigne l’oxygène dans le tableau périodique ?',
    choices: ['O', 'Ox', 'Og', 'Oy'],
    answerIndex: 0,
    explanation: 'Le symbole chimique de l’oxygène est O.',
    tags: ['science', 'chimie', 'subtheme:science:chemistry'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-science-earth-001',
    topicId: 'science',
    difficulty: 2,
    prompt: 'Sciences de la Terre : comment appelle-t-on la couche externe rigide de la Terre ?',
    choices: ['Lithosphère', 'Troposphère', 'Chromosphère', 'Hydrosphère'],
    answerIndex: 0,
    explanation: 'La lithosphère regroupe la croûte et la partie supérieure rigide du manteau.',
    tags: ['science', 'terre', 'geologie', 'subtheme:science:earth'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-sport-team-001',
    topicId: 'sport',
    difficulty: 1,
    prompt: 'Sport collectif : dans quel sport joue-t-on traditionnellement à cinq contre cinq ?',
    choices: ['Basket-ball', 'Rugby à XV', 'Baseball', 'Volley-ball de plage'],
    answerIndex: 0,
    explanation: 'Le basket-ball oppose deux équipes de cinq joueurs sur le terrain.',
    tags: ['sport', 'basket-ball', 'subtheme:sport:team'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-arts-museum-001',
    topicId: 'arts',
    difficulty: 1,
    prompt: 'Musées : dans quelle ville se trouve le musée d’Orsay ?',
    choices: ['Paris', 'Lyon', 'Marseille', 'Nantes'],
    answerIndex: 0,
    explanation: 'Le musée d’Orsay se trouve à Paris, dans une ancienne gare.',
    tags: ['arts', 'musee', 'subtheme:arts:museums'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-cinema-movement-001',
    topicId: 'cinema',
    difficulty: 2,
    prompt: 'Cinéma : quel mouvement français est associé à Truffaut et Godard ?',
    choices: ['Nouvelle Vague', 'Dogme 95', 'Néo-réalisme', 'Expressionnisme allemand'],
    answerIndex: 0,
    explanation: 'La Nouvelle Vague renouvelle le cinéma français à partir de la fin des années 1950.',
    tags: ['cinema', 'mouvement', 'subtheme:cinema:movements'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-architecture-vocabulary-001',
    topicId: 'architecture',
    difficulty: 1,
    prompt: 'Architecture : comment appelle-t-on l’espace central d’une église entre l’entrée et le chœur ?',
    choices: ['La nef', 'Le parvis', 'La flèche', 'Le contrefort'],
    answerIndex: 0,
    explanation: 'La nef est l’espace principal où se rassemblent les fidèles.',
    tags: ['architecture', 'vocabulaire', 'subtheme:architecture:vocabulary'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-economy-finance-001',
    topicId: 'economy',
    difficulty: 2,
    prompt: 'Finance : comment appelle-t-on un emprunt émis par un État ou une entreprise ?',
    choices: ['Une obligation', 'Une facture', 'Un dividende', 'Une franchise'],
    answerIndex: 0,
    explanation: 'Une obligation est un titre de dette qui correspond à un emprunt.',
    tags: ['economie', 'finance', 'subtheme:economy:finance'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-nature-plants-001',
    topicId: 'nature',
    difficulty: 1,
    prompt: 'Plantes : quelle partie contient souvent les graines chez une plante à fleurs ?',
    choices: ['Le fruit', 'La racine', 'La tige', 'Le pollen'],
    answerIndex: 0,
    explanation: 'Le fruit protège et aide souvent à disperser les graines.',
    tags: ['nature', 'botanique', 'subtheme:nature:plants'],
    sourceLabel: 'Contenu original Kizz',
  },
  {
    id: 'sub-technology-software-001',
    topicId: 'technology',
    difficulty: 2,
    prompt: 'Logiciel : quel terme désigne une interface qui permet à deux programmes de communiquer ?',
    choices: ['API', 'OLED', 'SSD', 'NFC'],
    answerIndex: 0,
    explanation: 'Une API expose des fonctions ou données pour qu’un autre logiciel les utilise.',
    tags: ['technologie', 'logiciel', 'api', 'subtheme:technology:software'],
    sourceLabel: 'Contenu original Kizz',
  },
];
