import { QuestionSeed, Topic } from './domain';

export const economyTopic: Topic = {
  id: 'economy',
  title: 'Économie',
  subtitle: 'Marchés, monnaie et indicateurs',
  icon: 'Eco',
  color: '#62B36F',
};

export const economyQuestions: QuestionSeed[] = [
  { id: 'eco-001', topicId: 'economy', difficulty: 1, prompt: "Que mesure principalement le produit intérieur brut d'un pays ?", choices: ["La valeur des biens et services produits", 'Le nombre total de lois votées', 'La surface agricole', 'La population active uniquement'], answerIndex: 0, explanation: "Le PIB additionne la valeur de la production finale réalisée sur un territoire pendant une période donnée.", tags: ['pib', 'indicateurs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Produit_int%C3%A9rieur_brut' },
  { id: 'eco-002', topicId: 'economy', difficulty: 1, prompt: "L'inflation correspond à...", choices: ['Une baisse générale des prix', 'Une hausse générale et durable des prix', 'Une hausse du nombre de banques', 'Une baisse des salaires uniquement'], answerIndex: 1, explanation: "L'inflation désigne une augmentation du niveau général des prix, ce qui réduit le pouvoir d'achat de la monnaie.", tags: ['inflation', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Inflation' },
  { id: 'eco-003', topicId: 'economy', difficulty: 1, prompt: 'Quel acteur fixe les grands taux directeurs en zone euro ?', choices: ['La Banque centrale européenne', 'Le Parlement européen', 'La Cour de justice', 'Chaque mairie'], answerIndex: 0, explanation: "La Banque centrale européenne pilote la politique monétaire de la zone euro, notamment via les taux directeurs.", tags: ['banque-centrale', 'euro'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Banque_centrale_europ%C3%A9enne' },
  { id: 'eco-004', topicId: 'economy', difficulty: 1, prompt: "Quand l'offre augmente fortement alors que la demande reste stable, le prix tend souvent à...", choices: ['Monter automatiquement', 'Baisser', 'Disparaître', 'Devenir fixe par nature'], answerIndex: 1, explanation: "Toutes choses égales par ailleurs, une offre plus abondante exerce une pression à la baisse sur le prix.", tags: ['offre-demande', 'prix'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Offre_et_demande' },
  { id: 'eco-005', topicId: 'economy', difficulty: 1, prompt: "Quel indicateur rapporte le nombre de personnes sans emploi à la population active ?", choices: ["Le taux de chômage", "Le taux d'épargne", 'Le taux de change', 'Le taux de marge'], answerIndex: 0, explanation: "Le taux de chômage mesure la part des chômeurs dans la population active selon une définition statistique précise.", tags: ['emploi', 'indicateurs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_de_ch%C3%B4mage' },
  { id: 'eco-006', topicId: 'economy', difficulty: 1, prompt: 'Quelle monnaie est utilisée par la France métropolitaine ?', choices: ['Le franc', "L'euro", 'La livre sterling', 'Le dollar canadien'], answerIndex: 1, explanation: "La France utilise l'euro depuis la mise en circulation des billets et pièces en 2002.", tags: ['euro', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Euro' },
  { id: 'eco-007', topicId: 'economy', difficulty: 1, type: 'free-text', prompt: "Quel mot désigne l'argent mis de côté plutôt que consommé immédiatement ?", acceptedAnswers: ['épargne', 'epargne', 'l epargne', 'l’épargne'], explanation: "L'épargne correspond à la partie du revenu qui n'est pas consommée.", tags: ['epargne', 'budget'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/%C3%89pargne' },
  { id: 'eco-008', topicId: 'economy', difficulty: 1, prompt: "Une entreprise réalise un bénéfice quand...", choices: ['Ses recettes dépassent ses coûts', 'Ses coûts dépassent ses recettes', 'Elle vend à perte', 'Elle ferme ses comptes'], answerIndex: 0, explanation: "Le bénéfice est un résultat positif : les produits sont supérieurs aux charges.", tags: ['entreprise', 'profit'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/B%C3%A9n%C3%A9fice' },

  { id: 'eco-009', topicId: 'economy', difficulty: 2, prompt: "Le taux d'intérêt réel se calcule approximativement en retirant quoi au taux nominal ?", choices: ["L'inflation", 'La population', 'Le nombre de banques', 'Le PIB en volume'], answerIndex: 0, explanation: "Le taux réel estime le rendement corrigé de l'inflation : taux nominal moins inflation attendue ou constatée.", tags: ['taux-interet', 'inflation'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_d%27int%C3%A9r%C3%AAt_r%C3%A9el' },
  { id: 'eco-010', topicId: 'economy', difficulty: 2, prompt: 'Une obligation est principalement...', choices: ['Un titre de dette', 'Une action avec droit de vote', 'Une monnaie locale', 'Un impôt indirect'], answerIndex: 0, explanation: "Une obligation représente une dette : l'émetteur emprunte et promet des paiements selon des conditions définies.", tags: ['finance', 'obligations'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Obligation_(finance)' },
  { id: 'eco-011', topicId: 'economy', difficulty: 2, prompt: "Quelle différence simple existe entre déficit public et dette publique ?", choices: ['Le déficit est un flux annuel, la dette un stock accumulé', 'La dette est toujours nulle', 'Le déficit mesure les exportations', 'Ce sont deux synonymes parfaits'], answerIndex: 0, explanation: "Le déficit est un solde négatif sur une période ; la dette additionne les emprunts passés encore dus.", tags: ['finances-publiques', 'dette'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Dette_publique' },
  { id: 'eco-012', topicId: 'economy', difficulty: 2, prompt: 'Un impôt progressif signifie que...', choices: ['Le taux augmente avec la base imposable', 'Tout le monde paie exactement la même somme', 'Il baisse quand le revenu augmente', 'Il est payé uniquement par les entreprises'], answerIndex: 0, explanation: "La progressivité fait croître le taux ou la charge relative avec le revenu ou la base taxée.", tags: ['fiscalite', 'impot'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Imp%C3%B4t_progressif' },
  { id: 'eco-013', topicId: 'economy', difficulty: 2, prompt: 'La productivité mesure surtout...', choices: ["La production rapportée aux ressources utilisées", 'La couleur des billets', 'Le nombre de ministères', "Le prix d'une seule action"], answerIndex: 0, explanation: "La productivité compare une production obtenue aux facteurs mobilisés, par exemple par heure travaillée.", tags: ['productivite', 'croissance'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Productivit%C3%A9' },
  { id: 'eco-014', topicId: 'economy', difficulty: 2, prompt: "Le taux de change indique...", choices: ["Le prix d'une monnaie exprimé dans une autre", "La durée d'un crédit", "Le niveau d'un impôt local", "La part d'un secteur dans le PIB"], answerIndex: 0, explanation: "Un taux de change exprime la valeur relative entre deux monnaies, par exemple euro contre dollar.", tags: ['change', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_de_change' },
  { id: 'eco-015', topicId: 'economy', difficulty: 2, type: 'free-text', prompt: "Quel terme désigne une hausse forte et auto-entretenue des prix ?", acceptedAnswers: ['inflation', 'hyperinflation', 'hyper inflation'], explanation: "Dans le langage courant on parle d'inflation ; lorsqu'elle devient extrême et rapide, on parle d'hyperinflation.", tags: ['inflation', 'vocabulaire'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Hyperinflation' },
  { id: 'eco-016', topicId: 'economy', difficulty: 2, prompt: "Dans un marché concurrentiel, un prix sert notamment à...", choices: ['Transmettre de l’information sur rareté et préférences', 'Supprimer toute décision', 'Garantir zéro risque', 'Remplacer la comptabilité'], answerIndex: 0, explanation: "Les prix coordonnent des décisions décentralisées en signalant rareté, demande et coûts relatifs.", tags: ['marche', 'prix'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Prix' },

  { id: 'eco-017', topicId: 'economy', difficulty: 3, prompt: "L'assouplissement quantitatif consiste principalement pour une banque centrale à...", choices: ['Acheter des actifs financiers pour injecter de la liquidité', 'Fermer les banques commerciales', 'Interdire les exportations', 'Fixer tous les salaires'], answerIndex: 0, explanation: "Le quantitative easing augmente la liquidité et cherche à influencer les taux longs via des achats d'actifs.", tags: ['banque-centrale', 'qe'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Assouplissement_quantitatif' },
  { id: 'eco-018', topicId: 'economy', difficulty: 3, prompt: "Une courbe des taux inversée signifie souvent que...", choices: ['Les taux courts dépassent les taux longs', 'Tous les taux valent zéro', 'Les obligations disparaissent', 'Les actions deviennent garanties'], answerIndex: 0, explanation: "Une inversion peut signaler des anticipations de ralentissement, car les taux longs passent sous les taux courts.", tags: ['finance', 'taux'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Courbe_des_taux' },
  { id: 'eco-019', topicId: 'economy', difficulty: 3, prompt: 'Le compte courant de la balance des paiements inclut notamment...', choices: ['Biens, services et revenus avec le reste du monde', 'Uniquement les billets en circulation', 'Les votes au parlement', 'Les températures mensuelles'], answerIndex: 0, explanation: "Le compte courant retrace les échanges de biens, services, revenus et transferts courants avec l'extérieur.", tags: ['commerce-international', 'balance-paiements'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Balance_des_paiements' },
  { id: 'eco-020', topicId: 'economy', difficulty: 3, prompt: "L'avantage comparatif explique qu'un pays gagne à se spécialiser dans...", choices: ["Ce qu'il produit au coût d'opportunité relatif le plus faible", "Ce qu'il produit le plus cher", 'Tout ce que produit son voisin', 'Uniquement les biens de luxe'], answerIndex: 0, explanation: "La théorie de Ricardo montre que l'échange peut être bénéfique même si un pays est moins productif partout.", tags: ['commerce-international', 'ricardo'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Avantage_comparatif' },
  { id: 'eco-021', topicId: 'economy', difficulty: 3, prompt: "L'aléa moral apparaît quand...", choices: ["Un acteur prend plus de risques car il ne supporte pas toutes les conséquences", 'Tous les contrats sont publics', 'Le risque est impossible', 'Les prix sont parfaitement stables'], answerIndex: 0, explanation: "L'aléa moral naît d'une asymétrie d'information après contrat : la protection change le comportement de risque.", tags: ['risque', 'information'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Al%C3%A9a_moral' },
  { id: 'eco-022', topicId: 'economy', difficulty: 3, prompt: 'La stagflation combine...', choices: ['Inflation élevée et faible croissance ou chômage', 'Déflation et plein emploi garanti', 'Croissance forte et prix stables uniquement', 'Exportations nulles et dette nulle'], answerIndex: 0, explanation: "La stagflation est une situation difficile où hausse des prix et stagnation économique coexistent.", tags: ['inflation', 'conjoncture'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Stagflation' },
  { id: 'eco-023', topicId: 'economy', difficulty: 3, type: 'multi-text', prompt: 'Associe les deux notions macroéconomiques.', answerFields: [{ id: 'flow', label: 'Solde négatif annuel', acceptedAnswers: ['déficit', 'deficit', 'déficit public', 'deficit public'] }, { id: 'stock', label: 'Accumulation des emprunts passés', acceptedAnswers: ['dette', 'dette publique'] }], explanation: 'Le déficit est un flux mesuré sur une période ; la dette est un stock hérité des déficits et remboursements passés.', tags: ['finances-publiques', 'multi-champs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/D%C3%A9ficit_public' },
  { id: 'eco-024', topicId: 'economy', difficulty: 3, prompt: "Une externalité négative existe quand...", choices: ["Une activité impose un coût à des tiers non pris en compte dans le prix", 'Une entreprise publie ses comptes', "Un consommateur paie exactement le prix affiché", 'Un pays change de monnaie'], answerIndex: 0, explanation: "Pollution, bruit ou congestion sont des exemples où le coût social dépasse le coût privé.", tags: ['externalites', 'environnement'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Externalit%C3%A9' },
];
