import { QuestionSeed, Topic } from './domain';

export const economyTopic: Topic = {
  id: 'economy',
  title: 'Économie',
  subtitle: 'Marchés, monnaie et indicateurs',
  icon: 'Eco',
  color: '#62B36F',
};

export const economyQuestions: QuestionSeed[] = [
  { id: 'eco-001', topicId: 'economy', difficulty: 1, prompt: "Que mesure principalement le produit interieur brut d'un pays ?", choices: ["La valeur des biens et services produits", 'Le nombre total de lois votees', 'La surface agricole', 'La population active uniquement'], answerIndex: 0, explanation: "Le PIB additionne la valeur de la production finale realisee sur un territoire pendant une periode donnee.", tags: ['pib', 'indicateurs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Produit_int%C3%A9rieur_brut' },
  { id: 'eco-002', topicId: 'economy', difficulty: 1, prompt: "L'inflation correspond a...", choices: ['Une baisse generale des prix', 'Une hausse generale et durable des prix', 'Une hausse du nombre de banques', 'Une baisse des salaires uniquement'], answerIndex: 1, explanation: "L'inflation designe une augmentation du niveau general des prix, ce qui reduit le pouvoir d'achat de la monnaie.", tags: ['inflation', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Inflation' },
  { id: 'eco-003', topicId: 'economy', difficulty: 1, prompt: 'Quel acteur fixe les grands taux directeurs en zone euro ?', choices: ['La Banque centrale europeenne', 'Le Parlement europeen', 'La Cour de justice', 'Chaque mairie'], answerIndex: 0, explanation: "La Banque centrale europeenne pilote la politique monetaire de la zone euro, notamment via les taux directeurs.", tags: ['banque-centrale', 'euro'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Banque_centrale_europ%C3%A9enne' },
  { id: 'eco-004', topicId: 'economy', difficulty: 1, prompt: "Quand l'offre augmente fortement alors que la demande reste stable, le prix tend souvent a...", choices: ['Monter automatiquement', 'Baisser', 'Disparaitre', 'Devenir fixe par nature'], answerIndex: 1, explanation: "Toutes choses egales par ailleurs, une offre plus abondante exerce une pression a la baisse sur le prix.", tags: ['offre-demande', 'prix'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Offre_et_demande' },
  { id: 'eco-005', topicId: 'economy', difficulty: 1, prompt: "Quel indicateur rapporte le nombre de personnes sans emploi a la population active ?", choices: ["Le taux de chomage", "Le taux d'epargne", 'Le taux de change', 'Le taux de marge'], answerIndex: 0, explanation: "Le taux de chomage mesure la part des chomeurs dans la population active selon une definition statistique precise.", tags: ['emploi', 'indicateurs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_de_ch%C3%B4mage' },
  { id: 'eco-006', topicId: 'economy', difficulty: 1, prompt: 'Quelle monnaie est utilisee par la France metropolitaine ?', choices: ['Le franc', "L'euro", 'La livre sterling', 'Le dollar canadien'], answerIndex: 1, explanation: "La France utilise l'euro depuis la mise en circulation des billets et pieces en 2002.", tags: ['euro', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Euro' },
  { id: 'eco-007', topicId: 'economy', difficulty: 1, type: 'free-text', prompt: "Quel mot designe l'argent mis de cote plutot que consomme immediatement ?", acceptedAnswers: ['epargne', 'l epargne', 'épargne'], explanation: "L'epargne correspond a la partie du revenu qui n'est pas consommee.", tags: ['epargne', 'budget'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/%C3%89pargne' },
  { id: 'eco-008', topicId: 'economy', difficulty: 1, prompt: "Une entreprise realise un benefice quand...", choices: ['Ses recettes depassent ses couts', 'Ses couts depassent ses recettes', 'Elle vend a perte', 'Elle ferme ses comptes'], answerIndex: 0, explanation: "Le benefice est un resultat positif: les produits sont superieurs aux charges.", tags: ['entreprise', 'profit'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/B%C3%A9n%C3%A9fice' },

  { id: 'eco-009', topicId: 'economy', difficulty: 2, prompt: "Le taux d'interet reel se calcule approximativement en retirant quoi au taux nominal ?", choices: ["L'inflation", 'La population', 'Le nombre de banques', 'Le PIB en volume'], answerIndex: 0, explanation: "Le taux reel estime le rendement corrige de l'inflation: taux nominal moins inflation attendue ou constatee.", tags: ['taux-interet', 'inflation'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_d%27int%C3%A9r%C3%AAt_r%C3%A9el' },
  { id: 'eco-010', topicId: 'economy', difficulty: 2, prompt: 'Une obligation est principalement...', choices: ['Un titre de dette', 'Une action avec droit de vote', 'Une monnaie locale', 'Un impot indirect'], answerIndex: 0, explanation: "Une obligation represente une dette: l'emetteur emprunte et promet des paiements selon des conditions definies.", tags: ['finance', 'obligations'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Obligation_(finance)' },
  { id: 'eco-011', topicId: 'economy', difficulty: 2, prompt: "Quelle difference simple existe entre deficit public et dette publique ?", choices: ['Le deficit est un flux annuel, la dette un stock accumule', 'La dette est toujours nulle', 'Le deficit mesure les exportations', 'Ce sont deux synonymes parfaits'], answerIndex: 0, explanation: "Le deficit est un solde negatif sur une periode; la dette additionne les emprunts passes encore dus.", tags: ['finances-publiques', 'dette'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Dette_publique' },
  { id: 'eco-012', topicId: 'economy', difficulty: 2, prompt: 'Un impot progressif signifie que...', choices: ['Le taux augmente avec la base imposable', 'Tout le monde paie exactement la meme somme', 'Il baisse quand le revenu augmente', 'Il est paye uniquement par les entreprises'], answerIndex: 0, explanation: "La progressivite fait croitre le taux ou la charge relative avec le revenu ou la base taxee.", tags: ['fiscalite', 'impot'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Imp%C3%B4t_progressif' },
  { id: 'eco-013', topicId: 'economy', difficulty: 2, prompt: 'La productivite mesure surtout...', choices: ["La production rapportee aux ressources utilisees", 'La couleur des billets', 'Le nombre de ministeres', "Le prix d'une seule action"], answerIndex: 0, explanation: "La productivite compare une production obtenue aux facteurs mobilises, par exemple par heure travaillee.", tags: ['productivite', 'croissance'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Productivit%C3%A9' },
  { id: 'eco-014', topicId: 'economy', difficulty: 2, prompt: "Le taux de change indique...", choices: ["Le prix d'une monnaie exprime dans une autre", "La duree d'un credit", "Le niveau d'un impot local", "La part d'un secteur dans le PIB"], answerIndex: 0, explanation: "Un taux de change exprime la valeur relative entre deux monnaies, par exemple euro contre dollar.", tags: ['change', 'monnaie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Taux_de_change' },
  { id: 'eco-015', topicId: 'economy', difficulty: 2, type: 'free-text', prompt: "Quel terme designe une hausse forte et auto-entretenue des prix ?", acceptedAnswers: ['inflation', 'hyperinflation', 'hyper inflation'], explanation: "Dans le langage courant on parle d'inflation; lorsqu'elle devient extreme et rapide, on parle d'hyperinflation.", tags: ['inflation', 'vocabulaire'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Hyperinflation' },
  { id: 'eco-016', topicId: 'economy', difficulty: 2, prompt: "Dans un marche concurrentiel, un prix sert notamment a...", choices: ['Transmettre de l information sur rarete et preferences', 'Supprimer toute decision', 'Garantir zero risque', 'Remplacer la comptabilite'], answerIndex: 0, explanation: "Les prix coordonnent des decisions decentralisees en signalant rarete, demande et couts relatifs.", tags: ['marche', 'prix'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Prix' },

  { id: 'eco-017', topicId: 'economy', difficulty: 3, prompt: "L'assouplissement quantitatif consiste principalement pour une banque centrale a...", choices: ['Acheter des actifs financiers pour injecter de la liquidite', 'Fermer les banques commerciales', 'Interdire les exportations', 'Fixer tous les salaires'], answerIndex: 0, explanation: "Le quantitative easing augmente la liquidite et cherche a influencer les taux longs via des achats d'actifs.", tags: ['banque-centrale', 'qe'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Assouplissement_quantitatif' },
  { id: 'eco-018', topicId: 'economy', difficulty: 3, prompt: "Une courbe des taux inversee signifie souvent que...", choices: ['Les taux courts depassent les taux longs', 'Tous les taux valent zero', 'Les obligations disparaissent', 'Les actions deviennent garanties'], answerIndex: 0, explanation: "Une inversion peut signaler des anticipations de ralentissement, car les taux longs passent sous les taux courts.", tags: ['finance', 'taux'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Courbe_des_taux' },
  { id: 'eco-019', topicId: 'economy', difficulty: 3, prompt: 'Le compte courant de la balance des paiements inclut notamment...', choices: ['Biens, services et revenus avec le reste du monde', 'Uniquement les billets en circulation', 'Les votes au parlement', 'Les temperatures mensuelles'], answerIndex: 0, explanation: "Le compte courant retrace les echanges de biens, services, revenus et transferts courants avec l'exterieur.", tags: ['commerce-international', 'balance-paiements'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Balance_des_paiements' },
  { id: 'eco-020', topicId: 'economy', difficulty: 3, prompt: "L'avantage comparatif explique qu'un pays gagne a se specialiser dans...", choices: ["Ce qu'il produit au cout d'opportunite relatif le plus faible", "Ce qu'il produit le plus cher", 'Tout ce que produit son voisin', 'Uniquement les biens de luxe'], answerIndex: 0, explanation: "La theorie de Ricardo montre que l'echange peut etre benefique meme si un pays est moins productif partout.", tags: ['commerce-international', 'ricardo'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Avantage_comparatif' },
  { id: 'eco-021', topicId: 'economy', difficulty: 3, prompt: "L'alea moral apparait quand...", choices: ["Un acteur prend plus de risques car il ne supporte pas toutes les consequences", 'Tous les contrats sont publics', 'Le risque est impossible', 'Les prix sont parfaitement stables'], answerIndex: 0, explanation: "L'alea moral nait d'une asymetrie d'information apres contrat: la protection change le comportement de risque.", tags: ['risque', 'information'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Al%C3%A9a_moral' },
  { id: 'eco-022', topicId: 'economy', difficulty: 3, prompt: 'La stagflation combine...', choices: ['Inflation elevee et faible croissance ou chomage', 'Deflation et plein emploi garanti', 'Croissance forte et prix stables uniquement', 'Exportations nulles et dette nulle'], answerIndex: 0, explanation: "La stagflation est une situation difficile ou hausse des prix et stagnation economique coexistent.", tags: ['inflation', 'conjoncture'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Stagflation' },
  { id: 'eco-023', topicId: 'economy', difficulty: 3, type: 'multi-text', prompt: 'Associe les deux notions macroeconomiques.', answerFields: [{ id: 'flow', label: 'Solde negatif annuel', acceptedAnswers: ['deficit', 'déficit', 'deficit public', 'déficit public'] }, { id: 'stock', label: 'Accumulation des emprunts passes', acceptedAnswers: ['dette', 'dette publique'] }], explanation: 'Le deficit est un flux mesure sur une periode; la dette est un stock herite des deficits et remboursements passes.', tags: ['finances-publiques', 'multi-champs'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/D%C3%A9ficit_public' },
  { id: 'eco-024', topicId: 'economy', difficulty: 3, prompt: "Une externalite negative existe quand...", choices: ["Une activite impose un cout a des tiers non pris en compte dans le prix", 'Une entreprise publie ses comptes', "Un consommateur paie exactement le prix affiche", 'Un pays change de monnaie'], answerIndex: 0, explanation: "Pollution, bruit ou congestion sont des exemples ou le cout social depasse le cout prive.", tags: ['externalites', 'environnement'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Externalit%C3%A9' },
];
