import { QuestionSeed, Topic } from './domain';

export const astronomyTopic: Topic = {
  id: 'astronomy',
  title: 'Astronomie',
  subtitle: 'Systeme solaire, etoiles et observation',
  icon: 'Ast',
  color: '#6F8CFF',
};

export const astronomyQuestions: QuestionSeed[] = [
  {
    id: 'astro-001',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planete est la plus proche du Soleil ?',
    choices: ['Venus', 'Mercure', 'Mars', 'Terre'],
    answerIndex: 1,
    explanation: 'Mercure est la planete la plus proche du Soleil.',
    tags: ['astronomie', 'systeme-solaire', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Mercure_(plan%C3%A8te)',
  },
  {
    id: 'astro-002',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planete est surnommee la planete rouge ?',
    choices: ['Jupiter', 'Mars', 'Saturne', 'Neptune'],
    answerIndex: 1,
    explanation: 'Mars doit sa couleur rougeatre aux oxydes de fer presents a sa surface.',
    tags: ['astronomie', 'mars', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)',
  },
  {
    id: 'astro-003',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planete possede les anneaux les plus spectaculaires visibles depuis la Terre ?',
    choices: ['Saturne', 'Mercure', 'Venus', 'Mars'],
    answerIndex: 0,
    explanation: 'Saturne est celebre pour son vaste systeme d anneaux.',
    tags: ['astronomie', 'saturne', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)',
  },
  {
    id: 'astro-004',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quel astre est une etoile au centre de notre systeme solaire ?',
    choices: ['La Lune', 'Le Soleil', 'Jupiter', 'Ceres'],
    answerIndex: 1,
    explanation: 'Le Soleil est une etoile autour de laquelle orbitent les planetes du systeme solaire.',
    tags: ['astronomie', 'soleil', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Soleil',
  },
  {
    id: 'astro-005',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quelle est la plus grande planete du systeme solaire ?',
    choices: ['Saturne', 'Jupiter', 'Neptune', 'Terre'],
    answerIndex: 1,
    explanation: 'Jupiter est la plus grande et la plus massive des planetes du systeme solaire.',
    tags: ['astronomie', 'jupiter', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Jupiter_(plan%C3%A8te)',
  },
  {
    id: 'astro-006',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quel instrument sert principalement a observer les astres lointains ?',
    choices: ['Un barometre', 'Un telescope', 'Un microscope', 'Un hygrometre'],
    answerIndex: 1,
    explanation: 'Le telescope collecte la lumiere des astres pour les observer avec plus de detail.',
    tags: ['astronomie', 'observation', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/T%C3%A9lescope',
  },
  {
    id: 'astro-007',
    topicId: 'astronomy',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Quel est le satellite naturel de la Terre ?',
    acceptedAnswers: ['la lune', 'lune'],
    explanation: 'La Lune est le seul satellite naturel permanent de la Terre.',
    tags: ['astronomie', 'lune', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Lune',
  },
  {
    id: 'astro-008',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quelle planete a une inclinaison axiale extreme, donnant l impression qu elle roule sur son orbite ?',
    choices: ['Uranus', 'Venus', 'Mars', 'Mercure'],
    answerIndex: 0,
    explanation: 'Uranus a un axe de rotation tres incline par rapport au plan de son orbite.',
    tags: ['astronomie', 'uranus', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Uranus_(plan%C3%A8te)',
  },
  {
    id: 'astro-009',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quelle mission Apollo a permis les premiers pas humains sur la Lune ?',
    choices: ['Apollo 8', 'Apollo 11', 'Apollo 13', 'Apollo 17'],
    answerIndex: 1,
    explanation: 'Apollo 11 a pose Neil Armstrong et Buzz Aldrin sur la Lune en juillet 1969.',
    tags: ['astronomie', 'lune', 'histoire-spatiale', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Apollo_11',
  },
  {
    id: 'astro-010',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quel phenomene se produit quand la Lune passe entre la Terre et le Soleil ?',
    choices: ['Eclipse solaire', 'Eclipse lunaire', 'Aurore polaire', 'Transit de Venus'],
    answerIndex: 0,
    explanation: 'Lors d une eclipse solaire, la Lune masque tout ou partie du Soleil depuis la Terre.',
    tags: ['astronomie', 'eclipse', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/%C3%89clipse_solaire',
  },
  {
    id: 'astro-011',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Combien de planetes principales compte le systeme solaire ?',
    choices: ['7', '8', '9', '10'],
    answerIndex: 1,
    explanation: 'Depuis le reclassement de Pluton, le systeme solaire compte huit planetes principales.',
    tags: ['astronomie', 'systeme-solaire', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Syst%C3%A8me_solaire',
  },
  {
    id: 'astro-012',
    topicId: 'astronomy',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Quel nom donne-t-on a une roche venue de l espace qui atteint le sol terrestre ?',
    acceptedAnswers: ['meteorite', 'météorite'],
    explanation: 'Une meteorite est un fragment d origine extraterrestre retrouve au sol.',
    tags: ['astronomie', 'meteorites', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/M%C3%A9t%C3%A9orite',
  },
  {
    id: 'astro-013',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planete est connue pour sa grande tache rouge ?',
    choices: ['Mars', 'Jupiter', 'Neptune', 'Venus'],
    answerIndex: 1,
    explanation: 'La grande tache rouge est une vaste tempete observee sur Jupiter.',
    tags: ['astronomie', 'jupiter', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Grande_Tache_rouge',
  },
  {
    id: 'astro-014',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Comment appelle-t-on la trajectoire d une planete autour du Soleil ?',
    choices: ['Une orbite', 'Un cratere', 'Une constellation', 'Une nebuleuse'],
    answerIndex: 0,
    explanation: 'L orbite est la trajectoire suivie par un astre autour d un autre.',
    tags: ['astronomie', 'orbite', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Orbite',
  },
  {
    id: 'astro-015',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quelle galaxie abrite le systeme solaire ?',
    choices: ['Andromede', 'La Voie lactee', 'Le Nuage de Magellan', 'La galaxie du Sombrero'],
    answerIndex: 1,
    explanation: 'Le systeme solaire se situe dans la Voie lactee.',
    tags: ['astronomie', 'galaxie', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Voie_lact%C3%A9e',
  },
  {
    id: 'astro-016',
    topicId: 'astronomy',
    difficulty: 3,
    type: 'free-text',
    prompt: 'Quel nom donne-t-on a un groupement apparent d etoiles comme Orion ?',
    acceptedAnswers: ['constellation', 'une constellation'],
    explanation: 'Une constellation est une figure apparente formee par des etoiles vues depuis la Terre.',
    tags: ['astronomie', 'constellations', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Constellation',
  },
];
