import { Difficulty, QuestionSeed } from './domain';

type TextEntry = {
  id: string;
  topicId: string;
  difficulty: Difficulty;
  prompt: string;
  acceptedAnswers: string[];
  explanation: string;
  tags: string[];
};

function textQuestion(entry: TextEntry): QuestionSeed {
  return {
    ...entry,
    type: 'free-text',
    sourceLabel: 'Contenu original Kizz - équilibrage formats',
    learnMoreUrl: `https://fr.wikipedia.org/w/index.php?search=${encodeURIComponent(entry.prompt)}`,
  };
}

export const formatBalanceQuestions: QuestionSeed[] = [
  textQuestion({ id: 'fmt-history-001', topicId: 'history', difficulty: 1, prompt: 'En quelle année commence la Révolution française ?', acceptedAnswers: ['1789'], explanation: 'La Révolution française débute en 1789, avec notamment les États généraux puis la prise de la Bastille.', tags: ['france', 'revolution', 'subtheme:history:france', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-002', topicId: 'history', difficulty: 1, prompt: 'Quel navigateur atteint les Caraïbes en 1492 ?', acceptedAnswers: ['christophe colomb', 'colomb'], explanation: 'Christophe Colomb atteint les Caraïbes en 1492 pour la couronne de Castille.', tags: ['exploration', 'xve-siecle', 'subtheme:history:world', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-003', topicId: 'history', difficulty: 1, prompt: 'Quelle ville est prise le 14 juillet 1789 comme symbole révolutionnaire ?', acceptedAnswers: ['la bastille', 'bastille'], explanation: 'La prise de la Bastille devient un symbole majeur de la Révolution française.', tags: ['france', 'revolution', 'subtheme:history:france', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-004', topicId: 'history', difficulty: 1, prompt: 'Quel empire est dirigé par Auguste après 27 av. J.-C. ?', acceptedAnswers: ['empire romain', 'rome', 'romain'], explanation: 'Auguste fonde le principat, première forme du pouvoir impérial romain.', tags: ['antiquite', 'rome', 'subtheme:history:antiquity'] }),
  textQuestion({ id: 'fmt-history-005', topicId: 'history', difficulty: 1, prompt: 'Quel mur tombe à Berlin en 1989 ?', acceptedAnswers: ['mur de berlin', 'le mur de berlin'], explanation: 'La chute du mur de Berlin marque un tournant de la fin de la guerre froide.', tags: ['allemagne', 'xxe-siecle', 'subtheme:history:germany', 'subtheme:history:contemporary'] }),
  textQuestion({ id: 'fmt-history-006', topicId: 'history', difficulty: 2, prompt: 'Quel traité met fin à la Première Guerre mondiale avec l’Allemagne ?', acceptedAnswers: ['traite de versailles', 'versailles'], explanation: 'Le traité de Versailles est signé le 28 juin 1919.', tags: ['europe', 'xxe-siecle', 'subtheme:history:world', 'subtheme:history:contemporary'] }),
  textQuestion({ id: 'fmt-history-007', topicId: 'history', difficulty: 2, prompt: 'Quel souverain français promulgue l’édit de Nantes ?', acceptedAnswers: ['henri iv', 'henri 4'], explanation: 'Henri IV promulgue l’édit de Nantes en 1598 pour encadrer la coexistence religieuse.', tags: ['france', 'religions', 'subtheme:history:france', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-008', topicId: 'history', difficulty: 2, prompt: 'Quelle capitale byzantine tombe en 1453 ?', acceptedAnswers: ['constantinople'], explanation: 'Constantinople est prise par les Ottomans en 1453.', tags: ['moyen-age', 'ottomans', 'subtheme:history:medieval'] }),
  textQuestion({ id: 'fmt-history-009', topicId: 'history', difficulty: 2, prompt: 'Quel mouvement intellectuel européen du XVIIIe siècle associe Voltaire et Montesquieu ?', acceptedAnswers: ['lumieres', 'les lumieres', 'siecle des lumieres'], explanation: 'Les Lumières promeuvent raison critique, sciences et réforme politique.', tags: ['france', 'europe', 'subtheme:history:france', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-010', topicId: 'history', difficulty: 2, prompt: 'Quel nom porte la période de tension entre États-Unis et URSS après 1945 ?', acceptedAnswers: ['guerre froide', 'la guerre froide'], explanation: 'La guerre froide oppose deux blocs sans conflit direct généralisé entre les superpuissances.', tags: ['xxe-siecle', 'subtheme:history:world', 'subtheme:history:contemporary'] }),
  textQuestion({ id: 'fmt-history-011', topicId: 'history', difficulty: 2, prompt: 'Quelle cité antique est ensevelie par l’éruption du Vésuve en 79 ?', acceptedAnswers: ['pompei', 'pompéi'], explanation: 'Pompéi est ensevelie par l’éruption du Vésuve, ce qui conserve une partie de la ville antique.', tags: ['italie', 'antiquite', 'subtheme:history:italy', 'subtheme:history:antiquity'] }),
  textQuestion({ id: 'fmt-history-012', topicId: 'history', difficulty: 2, prompt: 'Quel chef mongol fonde un immense empire au XIIIe siècle ?', acceptedAnswers: ['gengis khan', 'chinggis khan'], explanation: 'Gengis Khan unifie les tribus mongoles et lance de vastes conquêtes.', tags: ['asie', 'moyen-age', 'subtheme:history:world', 'subtheme:history:medieval'] }),
  textQuestion({ id: 'fmt-history-013', topicId: 'history', difficulty: 3, prompt: 'Quel congrès redessine l’Europe après la chute de Napoléon Ier ?', acceptedAnswers: ['congres de vienne', 'vienne'], explanation: 'Le congrès de Vienne organise l’équilibre européen après les guerres napoléoniennes.', tags: ['europe', 'xixe-siecle', 'subtheme:history:world', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-014', topicId: 'history', difficulty: 3, prompt: 'Quel texte anglais de 1215 limite symboliquement le pouvoir royal ?', acceptedAnswers: ['magna carta', 'grande charte'], explanation: 'La Magna Carta impose au roi Jean sans Terre des limites reconnues par écrit.', tags: ['angleterre', 'moyen-age', 'subtheme:history:medieval'] }),
  textQuestion({ id: 'fmt-history-015', topicId: 'history', difficulty: 3, prompt: 'Quel empire mésoaméricain a Tenochtitlan pour capitale ?', acceptedAnswers: ['azteque', 'aztèque', 'empire azteque', 'empire aztèque'], explanation: 'Tenochtitlan est la capitale insulaire de l’Empire aztèque.', tags: ['ameriques', 'subtheme:history:world'] }),
  textQuestion({ id: 'fmt-history-016', topicId: 'history', difficulty: 3, prompt: 'Quel terme désigne la période de transition entre Paléolithique et Néolithique ?', acceptedAnswers: ['mesolithique', 'mésolithique'], explanation: 'Le Mésolithique correspond à une période intermédiaire avant la généralisation de l’agriculture.', tags: ['prehistoire', 'subtheme:history:prehistory'] }),
  textQuestion({ id: 'fmt-history-017', topicId: 'history', difficulty: 3, prompt: 'Quel ministre de Louis XIII renforce l’autorité royale au XVIIe siècle ?', acceptedAnswers: ['richelieu', 'cardinal richelieu'], explanation: 'Richelieu mène une politique de renforcement de l’État royal.', tags: ['france', 'xviie-siecle', 'subtheme:history:france', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-018', topicId: 'history', difficulty: 3, prompt: 'Quel événement de 1917 renverse le tsarisme en Russie ?', acceptedAnswers: ['revolution russe', 'révolution russe', 'revolution de fevrier', 'révolution de février'], explanation: 'La révolution de février 1917 provoque l’abdication de Nicolas II.', tags: ['russie', 'xxe-siecle', 'subtheme:history:world', 'subtheme:history:contemporary'] }),
  textQuestion({ id: 'fmt-history-019', topicId: 'history', difficulty: 3, prompt: 'Quelle bataille de 732 est associée à Charles Martel ?', acceptedAnswers: ['poitiers', 'bataille de poitiers'], explanation: 'La bataille de Poitiers est traditionnellement associée à Charles Martel.', tags: ['france', 'moyen-age', 'subtheme:history:france', 'subtheme:history:medieval'] }),
  textQuestion({ id: 'fmt-history-020', topicId: 'history', difficulty: 3, prompt: 'Quel nom donne-t-on aux guerres entre Rome et Carthage ?', acceptedAnswers: ['guerres puniques', 'puniques'], explanation: 'Les guerres puniques opposent Rome et Carthage entre le IIIe et le IIe siècle av. J.-C.', tags: ['antiquite', 'rome', 'subtheme:history:antiquity'] }),

  textQuestion({ id: 'fmt-science-001', topicId: 'science', difficulty: 1, prompt: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', acceptedAnswers: ['dioxyde de carbone', 'co2'], explanation: 'La photosynthèse utilise du dioxyde de carbone, de l’eau et de la lumière.', tags: ['biologie', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-002', topicId: 'science', difficulty: 1, prompt: 'Quelle unité mesure une force dans le système international ?', acceptedAnswers: ['newton', 'le newton'], explanation: 'Le newton est l’unité SI de force; il relie masse et accélération dans la mécanique classique.', tags: ['physique', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-003', topicId: 'science', difficulty: 1, prompt: 'Quel symbole chimique correspond à l’oxygène ?', acceptedAnswers: ['o'], explanation: 'L’oxygène a pour symbole O dans le tableau périodique.', tags: ['chimie', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-004', topicId: 'science', difficulty: 1, prompt: 'Quel organe pompe le sang chez l’humain ?', acceptedAnswers: ['coeur', 'cœur', 'le coeur', 'le cœur'], explanation: 'Le cœur assure la circulation sanguine par ses contractions.', tags: ['biologie', 'corps-humain', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-005', topicId: 'science', difficulty: 1, prompt: 'Quelle planète est la plus proche du Soleil ?', acceptedAnswers: ['mercure'], explanation: 'Mercure est la planète la plus proche du Soleil.', tags: ['astronomie', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-006', topicId: 'science', difficulty: 2, prompt: 'Quelle molécule porte principalement l’information génétique ?', acceptedAnswers: ['adn', 'dna'], explanation: 'L’ADN stocke l’information génétique de nombreux organismes.', tags: ['biologie', 'genetique', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-007', topicId: 'science', difficulty: 2, prompt: 'Quel nombre atomique correspond au carbone ?', acceptedAnswers: ['6', 'six'], explanation: 'Le carbone possède 6 protons, donc un numéro atomique de 6.', tags: ['chimie', 'numero-atomique', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-008', topicId: 'science', difficulty: 2, prompt: 'Quelle unité mesure la résistance électrique ?', acceptedAnswers: ['ohm', 'l ohm'], explanation: 'La résistance électrique se mesure en ohms.', tags: ['physique', 'electricite', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-009', topicId: 'science', difficulty: 2, prompt: 'Quel processus divise une cellule en deux cellules filles proches ?', acceptedAnswers: ['mitose', 'la mitose'], explanation: 'La mitose répartit les chromosomes dupliqués dans deux cellules filles.', tags: ['biologie', 'cellule', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-010', topicId: 'science', difficulty: 2, prompt: 'Quelle formule chimique correspond au méthane ?', acceptedAnswers: ['ch4'], explanation: 'Le méthane est composé d’un atome de carbone et de quatre atomes d’hydrogène.', tags: ['chimie', 'formule', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-011', topicId: 'science', difficulty: 2, prompt: 'Quel type d’onde transporte la lumière visible ?', acceptedAnswers: ['onde electromagnetique', 'onde électromagnétique'], explanation: 'La lumière visible est une onde électromagnétique.', tags: ['physique', 'optique', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-012', topicId: 'science', difficulty: 2, prompt: 'Quel minéral est principalement composé de carbonate de calcium ?', acceptedAnswers: ['calcite', 'la calcite'], explanation: 'La calcite est une forme cristalline du carbonate de calcium.', tags: ['terre', 'geologie', 'subtheme:science:earth'] }),
  textQuestion({ id: 'fmt-science-013', topicId: 'science', difficulty: 3, prompt: 'Quel nombre quantique décrit la forme d’une orbitale atomique ?', acceptedAnswers: ['azimutal', 'nombre quantique azimutal'], explanation: 'Le nombre quantique azimutal l décrit le type et la forme de l’orbitale.', tags: ['chimie', 'configuration-electronique', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-014', topicId: 'science', difficulty: 3, prompt: 'Quelle loi relie pression et volume d’un gaz à température constante ?', acceptedAnswers: ['boyle-mariotte', 'loi de boyle-mariotte', 'boyle mariotte'], explanation: 'La loi de Boyle-Mariotte indique que pression et volume varient inversement à température constante.', tags: ['physique', 'thermodynamique', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-015', topicId: 'science', difficulty: 3, prompt: 'Quel organite produit la majorité de l’ATP cellulaire ?', acceptedAnswers: ['mitochondrie', 'la mitochondrie'], explanation: 'La mitochondrie produit l’ATP par respiration cellulaire.', tags: ['biologie', 'cellule', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-016', topicId: 'science', difficulty: 3, prompt: 'Quel isotope de l’hydrogène possède deux neutrons ?', acceptedAnswers: ['tritium', 'le tritium'], explanation: 'Le tritium est l’isotope de l’hydrogène avec un proton et deux neutrons.', tags: ['chimie', 'isotopes', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-017', topicId: 'science', difficulty: 3, prompt: 'Quel type de liaison met en commun des électrons entre atomes ?', acceptedAnswers: ['covalente', 'liaison covalente'], explanation: 'Une liaison covalente repose sur le partage d’électrons.', tags: ['chimie', 'liaison', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-018', topicId: 'science', difficulty: 3, prompt: 'Quel phénomène décale vers le rouge la lumière des galaxies lointaines ?', acceptedAnswers: ['redshift', 'decalage vers le rouge', 'décalage vers le rouge'], explanation: 'Le décalage vers le rouge cosmologique accompagne l’expansion de l’Univers.', tags: ['physique', 'astronomie', 'subtheme:science:physics'] }),

  textQuestion({ id: 'fmt-sport-001', topicId: 'sport', difficulty: 1, prompt: 'Combien de joueurs une équipe de football aligne-t-elle au coup d’envoi ?', acceptedAnswers: ['11', 'onze'], explanation: 'Une équipe de football commence avec onze joueurs.', tags: ['football', 'subtheme:sport:football'] }),
  textQuestion({ id: 'fmt-sport-002', topicId: 'sport', difficulty: 2, prompt: 'Quelle distance officielle mesure un marathon ?', acceptedAnswers: ['42,195 km', '42.195 km', '42,195 kilometres', '42.195 kilometres'], explanation: 'La distance officielle du marathon est de 42,195 kilomètres.', tags: ['athletisme', 'athlétisme', 'subtheme:sport:athletics'] }),
  textQuestion({ id: 'fmt-sport-003', topicId: 'sport', difficulty: 3, prompt: 'Au judo, quel mot japonais désigne le point complet qui arrête immédiatement le combat ?', acceptedAnswers: ['ippon', 'un ippon'], explanation: 'Un ippon donne immédiatement la victoire dans un combat de judo.', tags: ['judo', 'subtheme:sport:team'] }),

  textQuestion({ id: 'fmt-arts-001', topicId: 'arts', difficulty: 1, prompt: 'Qui a peint La Nuit étoilée ?', acceptedAnswers: ['vincent van gogh', 'van gogh'], explanation: 'Vincent van Gogh peint La Nuit étoilée en 1889.', tags: ['peinture', 'subtheme:arts:painting'] }),
  textQuestion({ id: 'fmt-arts-002', topicId: 'arts', difficulty: 2, prompt: 'Quel sculpteur a créé Le Penseur ?', acceptedAnswers: ['rodin', 'auguste rodin'], explanation: 'Le Penseur est une sculpture majeure d’Auguste Rodin.', tags: ['sculpture', 'subtheme:arts:sculpture'] }),
  textQuestion({ id: 'fmt-arts-003', topicId: 'arts', difficulty: 3, prompt: 'Quel artiste est associé au suprématisme ?', acceptedAnswers: ['malevitch', 'kasimir malevitch'], explanation: 'Kasimir Malevitch fonde le suprématisme autour de formes géométriques simples.', tags: ['peinture', 'mouvements', 'subtheme:arts:painting'] }),

  textQuestion({ id: 'fmt-architecture-001', topicId: 'architecture', difficulty: 1, prompt: 'Dans quelle ville se trouve la tour Eiffel ?', acceptedAnswers: ['paris'], explanation: 'La tour Eiffel se trouve à Paris; c’est le repère architectural le plus immédiat de la capitale française.', tags: ['france', 'edifice', 'subtheme:architecture:buildings'] }),
  textQuestion({ id: 'fmt-architecture-002', topicId: 'architecture', difficulty: 2, prompt: 'Quel style architectural utilise souvent arcs brisés et arcs-boutants ?', acceptedAnswers: ['gothique', 'style gothique'], explanation: 'Le gothique emploie notamment arc brisé, voûtes d’ogives et arcs-boutants.', tags: ['styles', 'gothique', 'subtheme:architecture:styles'] }),
  textQuestion({ id: 'fmt-architecture-003', topicId: 'architecture', difficulty: 3, prompt: 'Quel architecte a conçu Fallingwater ?', acceptedAnswers: ['frank lloyd wright', 'wright'], explanation: 'Frank Lloyd Wright conçoit Fallingwater au-dessus d’une cascade en Pennsylvanie.', tags: ['architectes', 'organique', 'subtheme:architecture:architects'] }),

  textQuestion({ id: 'fmt-history-021', topicId: 'history', difficulty: 1, prompt: 'Quel peuple antique fonde traditionnellement Rome ?', acceptedAnswers: ['romains', 'les romains'], explanation: 'La tradition romaine rattache la fondation de Rome aux Romains et au mythe de Romulus.', tags: ['antiquite', 'rome', 'subtheme:history:antiquity'] }),
  textQuestion({ id: 'fmt-history-022', topicId: 'history', difficulty: 2, prompt: 'Quel terme désigne l’unification politique de l’Italie au XIXe siècle ?', acceptedAnswers: ['risorgimento', 'le risorgimento'], explanation: 'Le Risorgimento regroupe les mouvements qui conduisent à l’unité italienne au XIXe siècle.', tags: ['italie', 'xixe-siecle', 'subtheme:history:italy', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-023', topicId: 'history', difficulty: 2, prompt: 'Quel royaume médiéval est associé à Charlemagne ?', acceptedAnswers: ['franc', 'royaume franc', 'empire carolingien'], explanation: 'Charlemagne gouverne le monde franc avant de devenir empereur en 800.', tags: ['moyen-age', 'france', 'subtheme:history:medieval'] }),
  textQuestion({ id: 'fmt-history-024', topicId: 'history', difficulty: 3, prompt: 'Quel système politique athénien repose sur l’assemblée des citoyens ?', acceptedAnswers: ['democratie directe', 'démocratie directe'], explanation: 'Athènes pratique une démocratie directe où les citoyens participent eux-mêmes aux décisions.', tags: ['antiquite', 'grece', 'subtheme:history:antiquity'] }),
  textQuestion({ id: 'fmt-history-025', topicId: 'history', difficulty: 3, prompt: 'Quel traité de 1648 clôt une grande partie de la guerre de Trente Ans ?', acceptedAnswers: ['westphalie', 'traites de westphalie', 'traités de westphalie'], explanation: 'Les traités de Westphalie mettent fin à une large partie des conflits européens de la guerre de Trente Ans.', tags: ['europe', 'xviie-siecle', 'subtheme:history:world', 'subtheme:history:modern'] }),
  textQuestion({ id: 'fmt-history-026', topicId: 'history', difficulty: 3, prompt: 'Quel terme désigne la période de pierre taillée avant le Néolithique ?', acceptedAnswers: ['paleolithique', 'paléolithique'], explanation: 'Le Paléolithique précède le Néolithique et correspond aux sociétés de chasseurs-cueilleurs.', tags: ['prehistoire', 'subtheme:history:prehistory'] }),

  textQuestion({ id: 'fmt-science-019', topicId: 'science', difficulty: 2, prompt: 'Quelle particule du noyau porte une charge positive ?', acceptedAnswers: ['proton', 'le proton'], explanation: 'Le proton porte une charge positive et le numéro atomique compte les protons du noyau.', tags: ['physique', 'chimie', 'subtheme:science:chemistry'] }),
  textQuestion({ id: 'fmt-science-020', topicId: 'science', difficulty: 2, prompt: 'Quel acide nucléique est généralement traduit en protéine ?', acceptedAnswers: ['arn messager', 'arnm'], explanation: 'L’ARN messager transporte l’information issue de l’ADN vers les ribosomes pour la traduction.', tags: ['biologie', 'genetique', 'subtheme:science:biology'] }),
  textQuestion({ id: 'fmt-science-021', topicId: 'science', difficulty: 3, prompt: 'Quel principe interdit à deux fermions identiques le même état quantique ?', acceptedAnswers: ['pauli', 'principe de pauli', 'principe d exclusion de pauli'], explanation: 'Le principe d’exclusion de Pauli structure notamment le remplissage des orbitales électroniques.', tags: ['physique', 'quantique', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-022', topicId: 'science', difficulty: 3, prompt: 'Quelle constante relie énergie et fréquence d’un photon ?', acceptedAnswers: ['planck', 'constante de planck'], explanation: 'La constante de Planck apparaît dans E = hν, relation centrale de la physique quantique.', tags: ['physique', 'quantique', 'subtheme:science:physics'] }),
  textQuestion({ id: 'fmt-science-023', topicId: 'science', difficulty: 3, prompt: 'Quel nom porte l’unité SI de quantité de matière ?', acceptedAnswers: ['mole', 'la mole'], explanation: 'La mole mesure une quantité de matière liée au nombre d’Avogadro.', tags: ['chimie', 'unites', 'subtheme:science:chemistry'] }),

  textQuestion({ id: 'fmt-arts-004', topicId: 'arts', difficulty: 1, prompt: 'Quel musée parisien conserve La Joconde ?', acceptedAnswers: ['louvre', 'le louvre', 'musee du louvre', 'musée du louvre'], explanation: 'La Joconde est conservée au musée du Louvre, repère majeur de l’art à Paris.', tags: ['musee', 'peinture', 'subtheme:arts:painting'] }),
  textQuestion({ id: 'fmt-arts-005', topicId: 'arts', difficulty: 2, prompt: 'Quel mouvement est associé à Claude Monet ?', acceptedAnswers: ['impressionnisme', 'l impressionnisme'], explanation: 'Monet est une figure centrale de l’impressionnisme et de l’étude des effets de lumière.', tags: ['peinture', 'mouvements', 'subtheme:arts:painting'] }),
  textQuestion({ id: 'fmt-arts-006', topicId: 'arts', difficulty: 2, prompt: 'Quel compositeur a écrit la Neuvième Symphonie avec l’Ode à la joie ?', acceptedAnswers: ['beethoven', 'ludwig van beethoven'], explanation: 'Beethoven compose la Neuvième Symphonie, célèbre pour son finale choral.', tags: ['musique', 'subtheme:arts:music'] }),
  textQuestion({ id: 'fmt-arts-007', topicId: 'arts', difficulty: 3, prompt: 'Quel artiste néerlandais a peint Broadway Boogie-Woogie ?', acceptedAnswers: ['mondrian', 'piet mondrian'], explanation: 'Piet Mondrian peint Broadway Boogie-Woogie dans son langage géométrique tardif.', tags: ['peinture', 'abstraction', 'subtheme:arts:painting'] }),

  textQuestion({ id: 'fmt-nature-001', topicId: 'nature', difficulty: 1, prompt: 'Quel arbre produit des glands ?', acceptedAnswers: ['chene', 'chêne', 'le chene', 'le chêne'], explanation: 'Le chêne produit des glands, un repère simple pour identifier cet arbre.', tags: ['arbres', 'plantes', 'subtheme:nature:plants'] }),
  textQuestion({ id: 'fmt-nature-002', topicId: 'nature', difficulty: 2, prompt: 'Quel pigment vert permet aux plantes de capter la lumière ?', acceptedAnswers: ['chlorophylle', 'la chlorophylle'], explanation: 'La chlorophylle absorbe la lumière utilisée pendant la photosynthèse.', tags: ['plantes', 'biologie', 'subtheme:nature:plants'] }),
  textQuestion({ id: 'fmt-nature-003', topicId: 'nature', difficulty: 3, prompt: 'Quel terme désigne une relation bénéfique aux deux espèces ?', acceptedAnswers: ['mutualisme', 'le mutualisme'], explanation: 'Le mutualisme décrit une interaction où les deux espèces retirent un bénéfice.', tags: ['ecologie', 'subtheme:nature:ecosystems'] }),

  textQuestion({ id: 'fmt-technology-001', topicId: 'technology', difficulty: 2, prompt: 'Quel sigle désigne une interface de programmation applicative ?', acceptedAnswers: ['api', 'application programming interface'], explanation: 'Une API expose des fonctions ou données pour permettre à des logiciels de communiquer.', tags: ['logiciel', 'api', 'subtheme:technology:software'] }),
  textQuestion({ id: 'fmt-cinema-001', topicId: 'cinema', difficulty: 2, prompt: 'Quel terme désigne une prise sans coupe apparente sur toute une scène ?', acceptedAnswers: ['plan sequence', 'plan-séquence', 'plan séquence'], explanation: 'Le plan-séquence conserve la continuité d’une action sans montage visible.', tags: ['langage', 'mise-en-scene', 'subtheme:cinema:techniques'] }),

  textQuestion({ id: 'fmt-architecture-004', topicId: 'architecture', difficulty: 1, prompt: 'Quel élément vertical peut soutenir un entablement antique ?', acceptedAnswers: ['colonne', 'une colonne'], explanation: 'La colonne est un support vertical fréquent dans les architectures antiques et classiques.', tags: ['vocabulaire', 'subtheme:architecture:styles'] }),
  textQuestion({ id: 'fmt-architecture-005', topicId: 'architecture', difficulty: 2, prompt: 'Quel architecte catalan est associé à la Sagrada Família ?', acceptedAnswers: ['gaudi', 'gaudí', 'antoni gaudi', 'antoni gaudí'], explanation: 'Antoni Gaudí conçoit la Sagrada Família, repère majeur du modernisme catalan.', tags: ['architectes', 'espagne', 'subtheme:architecture:architects'] }),
  textQuestion({ id: 'fmt-architecture-006', topicId: 'architecture', difficulty: 2, prompt: 'Quel mouvement architectural valorise béton brut et volumes massifs ?', acceptedAnswers: ['brutalisme', 'le brutalisme'], explanation: 'Le brutalisme met en avant le béton apparent et des formes puissantes.', tags: ['styles', 'subtheme:architecture:styles'] }),
  textQuestion({ id: 'fmt-architecture-007', topicId: 'architecture', difficulty: 3, prompt: 'Quel architecte est associé à la Villa Rotonda ?', acceptedAnswers: ['palladio', 'andrea palladio'], explanation: 'Andrea Palladio conçoit la Villa Rotonda, modèle majeur de l’architecture palladienne.', tags: ['architectes', 'renaissance', 'subtheme:architecture:architects'] }),
  textQuestion({ id: 'fmt-architecture-008', topicId: 'architecture', difficulty: 3, prompt: 'Quel style emploie souvent voûtes d’ogives et élévation verticale ?', acceptedAnswers: ['gothique', 'style gothique'], explanation: 'Le style gothique associe élévation verticale, voûtes d’ogives et arcs-boutants.', tags: ['styles', 'gothique', 'subtheme:architecture:styles'] }),
];
