import { QuestionSeed, Topic } from './domain';

export const mvpTopics: Topic[] = [
  { id: 'nature', title: 'Nature', subtitle: 'Animaux, plantes et climat', icon: 'N', color: '#57B987' },
  { id: 'technology', title: 'Technologie', subtitle: 'Numérique et inventions', icon: 'T', color: '#5F82E8' },
  { id: 'cinema', title: 'Cinéma', subtitle: 'Films, métiers et langage', icon: 'C', color: '#DB6E88' },
  { id: 'daily', title: 'Vie pratique', subtitle: 'Repères utiles au quotidien', icon: 'V', color: '#E0A752' },
  { id: 'architecture', title: 'Architecture', subtitle: 'Édifices, styles et architectes', icon: 'Ar', color: '#C68A62' },
];

export const mvpQuestions: QuestionSeed[] = [
  { id: 'arc-01', topicId: 'architecture', difficulty: 1, prompt: 'Quel architecte a conçu la villa Savoye ?', choices: ['Le Corbusier', 'Frank Gehry', 'Antoni Gaudí', 'Ieoh Ming Pei'], answerIndex: 0, explanation: 'Le Corbusier conçoit la villa Savoye à Poissy comme manifeste de ses cinq points de l’architecture moderne.', tags: ['modernisme', 'france'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Villa_Savoye' },
  { id: 'arc-02', topicId: 'architecture', difficulty: 1, type: 'free-text', prompt: 'Dans quelle ville se trouve la Sagrada Família ?', acceptedAnswers: ['barcelone', 'barcelona'], explanation: 'La basilique conçue par Antoni Gaudí se situe à Barcelone.', tags: ['gaudí', 'espagne'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Sagrada_Família' },
  { id: 'arc-03', topicId: 'architecture', difficulty: 2, prompt: 'Quel élément caractérise particulièrement l’architecture gothique ?', choices: ['Le toit plat', 'L’arc-boutant', 'La colonne dorique', 'Le mur-rideau'], answerIndex: 1, explanation: 'L’arc-boutant reporte les poussées des voûtes et permet d’élever les murs percés de grandes verrières.', tags: ['gothique'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Arc-boutant' },
  { id: 'arc-04', topicId: 'architecture', difficulty: 2, prompt: 'Qui a conçu la pyramide du Louvre ?', choices: ['Jean Nouvel', 'Ieoh Ming Pei', 'Renzo Piano', 'Norman Foster'], answerIndex: 1, explanation: 'Ieoh Ming Pei conçoit la pyramide de verre inaugurée en 1989.', tags: ['musées', 'paris'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Pyramide_du_Louvre' },
  { id: 'arc-05', topicId: 'architecture', difficulty: 2, type: 'free-text', prompt: 'Quel style architectural est associé à des formes massives en béton brut ?', acceptedAnswers: ['brutalisme', 'brutaliste'], explanation: 'Le brutalisme met souvent en avant le béton brut, les volumes massifs et la structure constructive.', tags: ['xxe-siècle', 'styles'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Brutalisme' },
  { id: 'arc-06', topicId: 'architecture', difficulty: 3, prompt: 'Quel duo a conçu le Centre Pompidou à Paris ?', choices: ['Piano et Rogers', 'Herzog et de Meuron', 'Lacaton et Vassal', 'OMA et MVRDV'], answerIndex: 0, explanation: 'Renzo Piano et Richard Rogers remportent le concours du Centre Pompidou, inauguré en 1977.', tags: ['high-tech', 'paris'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Centre_national_d’art_et_de_culture_Georges-Pompidou' },
  { id: 'nat-01', topicId: 'nature', difficulty: 1, prompt: 'Quel mammifère est capable de voler activement ?', choices: ['L’écureuil volant', 'La chauve-souris', 'Le manchot', 'Le kiwi'], answerIndex: 1, explanation: 'La chauve-souris est le seul mammifère pratiquant un vol actif et soutenu.', tags: ['animaux'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Chiroptera' },
  { id: 'nat-02', topicId: 'nature', difficulty: 1, type: 'free-text', prompt: 'Comment appelle-t-on le passage de l’eau liquide à l’état gazeux ?', acceptedAnswers: ['évaporation', 'evaporation', 'vaporisation'], explanation: 'L’évaporation est une vaporisation progressive qui se produit à la surface d’un liquide.', tags: ['eau', 'climat'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Évaporation' },
  { id: 'nat-03', topicId: 'nature', difficulty: 1, prompt: 'Quelle partie d’une plante absorbe principalement l’eau du sol ?', choices: ['La fleur', 'Les feuilles', 'Les racines', 'Le fruit'], answerIndex: 2, explanation: 'Les racines puisent l’eau et les sels minéraux dans le sol.', tags: ['botanique'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Racine_(botanique)' },
  { id: 'nat-04', topicId: 'nature', difficulty: 2, prompt: 'Quel phénomène est principalement responsable des marées ?', choices: ['Le vent', 'La Lune', 'Les volcans', 'Le champ magnétique'], answerIndex: 1, explanation: 'L’attraction gravitationnelle de la Lune est la cause principale des marées terrestres.', tags: ['océans', 'astronomie'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Marée' },
  { id: 'nat-05', topicId: 'nature', difficulty: 2, type: 'free-text', prompt: 'Quel gaz constitue la plus grande part de l’atmosphère terrestre ?', acceptedAnswers: ['azote', 'diazote', 'n2'], explanation: 'Le diazote représente environ 78 % de l’atmosphère terrestre.', tags: ['atmosphère'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Atmosphère_terrestre' },
  { id: 'nat-06', topicId: 'nature', difficulty: 3, prompt: 'Quel biome est caractérisé par un pergélisol ?', choices: ['La savane', 'La toundra', 'La mangrove', 'La garrigue'], answerIndex: 1, explanation: 'La toundra repose souvent sur un sol gelé en permanence appelé pergélisol.', tags: ['climat', 'biomes'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Toundra' },

  { id: 'tech-01', topicId: 'technology', difficulty: 1, prompt: 'Que signifient les lettres « GPS » ?', choices: ['Global Positioning System', 'General Phone Service', 'Graphic Processing Signal', 'Global Power Source'], answerIndex: 0, explanation: 'GPS signifie Global Positioning System, un système de positionnement par satellites.', tags: ['navigation'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Global_Positioning_System' },
  { id: 'tech-02', topicId: 'technology', difficulty: 1, type: 'free-text', prompt: 'Quel composant stocke durablement les fichiers dans un téléphone ?', acceptedAnswers: ['stockage', 'mémoire flash', 'memoire flash', 'ssd'], explanation: 'Les téléphones utilisent généralement de la mémoire flash pour conserver les données sans alimentation.', tags: ['matériel'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Mémoire_flash' },
  { id: 'tech-03', topicId: 'technology', difficulty: 1, prompt: 'À quoi sert principalement un navigateur web ?', choices: ['Éditer des vidéos', 'Consulter des pages web', 'Recharger une batterie', 'Compresser des vêtements'], answerIndex: 1, explanation: 'Un navigateur récupère et affiche des ressources du Web.', tags: ['web'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Navigateur_web' },
  { id: 'tech-04', topicId: 'technology', difficulty: 2, prompt: 'Quel langage structure le contenu d’une page web ?', choices: ['HTML', 'SQL', 'Python', 'Bluetooth'], answerIndex: 0, explanation: 'HTML décrit la structure sémantique d’une page; CSS gère principalement sa présentation.', tags: ['web', 'code'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Hypertext_Markup_Language' },
  { id: 'tech-05', topicId: 'technology', difficulty: 2, type: 'free-text', prompt: 'Comment nomme-t-on une copie de données conservée en cas de perte ?', acceptedAnswers: ['sauvegarde', 'backup', 'copie de sauvegarde'], explanation: 'Une sauvegarde permet de restaurer des données après une panne, une erreur ou une perte.', tags: ['sécurité'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Sauvegarde_(informatique)' },
  { id: 'tech-06', topicId: 'technology', difficulty: 3, prompt: 'Quel principe protège un message en le rendant illisible sans clé ?', choices: ['La compression', 'Le chiffrement', 'La pagination', 'La virtualisation'], answerIndex: 1, explanation: 'Le chiffrement transforme les données afin que seules les personnes disposant de la clé puissent les lire.', tags: ['sécurité'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Chiffrement' },

  { id: 'cin-01', topicId: 'cinema', difficulty: 1, prompt: 'Qui dirige l’interprétation des acteurs et la mise en scène d’un film ?', choices: ['Le projectionniste', 'Le réalisateur', 'Le distributeur', 'Le critique'], answerIndex: 1, explanation: 'Le réalisateur coordonne les choix artistiques et la mise en scène du film.', tags: ['métiers'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Réalisateur' },
  { id: 'cin-02', topicId: 'cinema', difficulty: 1, type: 'free-text', prompt: 'Comment appelle-t-on la musique composée pour accompagner un film ?', acceptedAnswers: ['bande originale', 'bo', 'musique de film'], explanation: 'La bande originale rassemble la musique utilisée ou créée pour le film.', tags: ['musique'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Bande_originale' },
  { id: 'cin-03', topicId: 'cinema', difficulty: 1, prompt: 'Qu’est-ce qu’un gros plan montre généralement ?', choices: ['Un vaste paysage', 'Un visage ou un détail', 'Le générique entier', 'Les coulisses du cinéma'], answerIndex: 1, explanation: 'Le gros plan cadre étroitement un visage ou un objet pour attirer l’attention.', tags: ['langage'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Gros_plan' },
  { id: 'cin-04', topicId: 'cinema', difficulty: 2, prompt: 'Quel document décrit les scènes, dialogues et actions avant le tournage ?', choices: ['Le scénario', 'L’affiche', 'Le billet', 'La critique'], answerIndex: 0, explanation: 'Le scénario constitue la base écrite narrative et technique du film.', tags: ['écriture'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Scénario' },
  { id: 'cin-05', topicId: 'cinema', difficulty: 2, type: 'free-text', prompt: 'Quel mot désigne la suite organisée des plans d’un film ?', acceptedAnswers: ['montage', 'le montage'], explanation: 'Le montage sélectionne et assemble les plans pour construire le rythme et le récit.', tags: ['langage'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Montage' },
  { id: 'cin-06', topicId: 'cinema', difficulty: 3, prompt: 'À quelle cadence le cinéma sonore s’est-il largement standardisé ?', choices: ['12 images/s', '18 images/s', '24 images/s', '60 images/s'], answerIndex: 2, explanation: 'Le cinéma sonore s’est largement standardisé autour de 24 images par seconde.', tags: ['technique'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Cadence_de_prise_de_vues' },

  { id: 'day-01', topicId: 'daily', difficulty: 1, prompt: 'Quelle information permet d’identifier une date limite sur un produit alimentaire ?', choices: ['Le code postal', 'La DLC ou la DDM', 'Le prix au kilo', 'Le logo de la marque'], answerIndex: 1, explanation: 'La DLC et la DDM renseignent sur la limite de consommation ou de qualité optimale.', tags: ['alimentation'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Date_limite_de_consommation' },
  { id: 'day-02', topicId: 'daily', difficulty: 1, type: 'free-text', prompt: 'Combien de centilitres contient un litre ?', acceptedAnswers: ['100', 'cent', '100 cl'], explanation: 'Un litre correspond à 100 centilitres.', tags: ['mesures'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Litre' },
  { id: 'day-03', topicId: 'daily', difficulty: 1, prompt: 'Quel numéro d’urgence européen fonctionne dans toute l’Union européenne ?', choices: ['112', '118', '411', '911'], answerIndex: 0, explanation: 'Le 112 est le numéro d’appel d’urgence européen.', tags: ['sécurité'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/112_(numéro_d’appel_d’urgence)' },
  { id: 'day-04', topicId: 'daily', difficulty: 2, prompt: 'Que compare un prix affiché au kilogramme ?', choices: ['La durée de garantie', 'Le coût à quantité égale', 'La qualité nutritionnelle', 'La distance de transport'], answerIndex: 1, explanation: 'Le prix au kilogramme facilite la comparaison de formats et de marques à quantité égale.', tags: ['budget'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Prix' },
  { id: 'day-05', topicId: 'daily', difficulty: 2, type: 'free-text', prompt: 'Comment appelle-t-on l’argent mis de côté pour une dépense future ?', acceptedAnswers: ['épargne', 'epargne', 'économies', 'economies'], explanation: 'L’épargne est la part du revenu qui n’est pas immédiatement consommée.', tags: ['budget'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Épargne' },
  { id: 'day-06', topicId: 'daily', difficulty: 2, prompt: 'Quelle action réduit le risque lié à la perte d’un mot de passe unique ?', choices: ['Réutiliser le même partout', 'Utiliser un gestionnaire de mots de passe', 'L’écrire publiquement', 'Le raccourcir à quatre lettres'], answerIndex: 1, explanation: 'Un gestionnaire aide à créer et conserver des mots de passe différents et robustes.', tags: ['numérique', 'sécurité'], sourceLabel: 'Contenu original Kizz', learnMoreUrl: 'https://fr.wikipedia.org/wiki/Gestionnaire_de_mots_de_passe' },
];
