import { QuestionSeed, Topic } from './domain';

export const astronomyTopic: Topic = {
  id: 'astronomy',
  title: 'Astronomie',
  subtitle: 'Système solaire, étoiles et observation',
  icon: 'Ast',
  color: '#6F8CFF',
};

export const astronomyQuestions: QuestionSeed[] = [
  {
    id: 'astro-001',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planète du Système solaire orbite avant Vénus ?',
    choices: ['Vénus', 'Mercure', 'Mars', 'Terre'],
    answerIndex: 1,
    explanation: 'Mercure est la planète la plus proche du Soleil.',
    tags: ['astronomie', 'systeme-solaire', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Mercure_(plan%C3%A8te)',
  },
  {
    id: 'astro-002',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planète est surnommée la planète rouge ?',
    choices: ['Jupiter', 'Mars', 'Saturne', 'Neptune'],
    answerIndex: 1,
    explanation: 'Mars doit sa couleur rougeâtre aux oxydes de fer présents à sa surface.',
    tags: ['astronomie', 'mars', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)',
  },
  {
    id: 'astro-003',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planète possède les anneaux les plus spectaculaires visibles depuis la Terre ?',
    choices: ['Saturne', 'Mercure', 'Vénus', 'Mars'],
    answerIndex: 0,
    explanation: 'Saturne est célèbre pour son vaste système d’anneaux.',
    tags: ['astronomie', 'saturne', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)',
  },
  {
    id: 'astro-004',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quel astre est une étoile au centre de notre système solaire ?',
    choices: ['La Lune', 'Le Soleil', 'Jupiter', 'Cérès'],
    answerIndex: 1,
    explanation: 'Le Soleil est une étoile autour de laquelle orbitent les planètes du système solaire.',
    tags: ['astronomie', 'soleil', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Soleil',
  },
  {
    id: 'astro-005',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quelle est la plus grande planète du système solaire ?',
    choices: ['Saturne', 'Jupiter', 'Neptune', 'Terre'],
    answerIndex: 1,
    explanation: 'Jupiter est la plus grande et la plus massive des planètes du système solaire.',
    tags: ['astronomie', 'jupiter', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Jupiter_(plan%C3%A8te)',
  },
  {
    id: 'astro-006',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Quel instrument sert principalement à observer les astres lointains ?',
    choices: ['Un baromètre', 'Un télescope', 'Un microscope', 'Un hygromètre'],
    answerIndex: 1,
    explanation: 'Le télescope collecte la lumière des astres pour les observer avec plus de détail.',
    tags: ['astronomie', 'observation', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/T%C3%A9lescope',
  },
  {
    id: 'astro-007',
    topicId: 'astronomy',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Quel est le satellite naturel de la Terre ?',
    acceptedAnswers: ['la lune', 'lune'],
    explanation: 'La Lune est le seul satellite naturel permanent de la Terre.',
    tags: ['astronomie', 'lune', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Lune',
  },
  {
    id: 'astro-008',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quelle planète a une inclinaison axiale extrême, donnant l’impression qu’elle roule sur son orbite ?',
    choices: ['Uranus', 'Vénus', 'Mars', 'Mercure'],
    answerIndex: 0,
    explanation: 'Uranus a un axe de rotation très incliné par rapport au plan de son orbite.',
    tags: ['astronomie', 'uranus', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Uranus_(plan%C3%A8te)',
  },
  {
    id: 'astro-009',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle mission Apollo a permis les premiers pas humains sur la Lune ?',
    choices: ['Apollo 8', 'Apollo 11', 'Apollo 13', 'Apollo 17'],
    answerIndex: 1,
    explanation: 'Apollo 11 a posé Neil Armstrong et Buzz Aldrin sur la Lune en juillet 1969.',
    tags: ['astronomie', 'lune', 'histoire-spatiale', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Apollo_11',
  },
  {
    id: 'astro-010',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quel phénomène se produit quand la Lune passe entre la Terre et le Soleil ?',
    choices: ['Éclipse solaire', 'Éclipse lunaire', 'Aurore polaire', 'Transit de Vénus'],
    answerIndex: 0,
    explanation: 'Lors d’une éclipse solaire, la Lune masque tout ou partie du Soleil depuis la Terre.',
    tags: ['astronomie', 'eclipse', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/%C3%89clipse_solaire',
  },
  {
    id: 'astro-011',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Combien de planètes principales compte le système solaire ?',
    choices: ['7', '8', '9', '10'],
    answerIndex: 1,
    explanation: 'Depuis le reclassement de Pluton, le système solaire compte huit planètes principales.',
    tags: ['astronomie', 'systeme-solaire', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Syst%C3%A8me_solaire',
  },
  {
    id: 'astro-012',
    topicId: 'astronomy',
    difficulty: 2,
    type: 'free-text',
    prompt: 'Quel nom donne-t-on à une roche venue de l’espace qui atteint le sol terrestre ?',
    acceptedAnswers: ['météorite', 'meteorite'],
    explanation: 'Une météorite est un fragment d’origine extraterrestre retrouvé au sol.',
    tags: ['astronomie', 'meteorites', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/M%C3%A9t%C3%A9orite',
  },
  {
    id: 'astro-013',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle planète est connue pour sa grande tache rouge ?',
    choices: ['Mars', 'Jupiter', 'Neptune', 'Vénus'],
    answerIndex: 1,
    explanation: 'La grande tache rouge est une vaste tempête observée sur Jupiter.',
    tags: ['astronomie', 'jupiter', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Grande_Tache_rouge',
  },
  {
    id: 'astro-014',
    topicId: 'astronomy',
    difficulty: 2,
    prompt: 'Comment appelle-t-on la trajectoire d’une planète autour du Soleil ?',
    choices: ['Une orbite', 'Un cratère', 'Une constellation', 'Une nébuleuse'],
    answerIndex: 0,
    explanation: 'L’orbite est la trajectoire suivie par un astre autour d’un autre.',
    tags: ['astronomie', 'orbite', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Orbite',
  },
  {
    id: 'astro-015',
    topicId: 'astronomy',
    difficulty: 1,
    prompt: 'Quelle galaxie abrite le système solaire ?',
    choices: ['Andromède', 'La Voie lactée', 'Le Nuage de Magellan', 'La galaxie du Sombrero'],
    answerIndex: 1,
    explanation: 'Le système solaire se situe dans la Voie lactée.',
    tags: ['astronomie', 'galaxie', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Voie_lact%C3%A9e',
  },
  {
    id: 'astro-016',
    topicId: 'astronomy',
    difficulty: 1,
    type: 'free-text',
    prompt: 'Quel nom donne-t-on à un groupement apparent d’étoiles comme Orion ?',
    acceptedAnswers: ['constellation', 'une constellation'],
    explanation: 'Une constellation est une figure apparente formée par des étoiles vues depuis la Terre.',
    tags: ['astronomie', 'constellations', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Constellation',
  },
  {
    id: 'astro-017',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quel décalage spectral indique généralement qu’une galaxie lointaine s’éloigne de nous ?',
    choices: ['Décalage vers le rouge', 'Décalage vers le violet', 'Aberration chromatique', 'Précession des équinoxes'],
    answerIndex: 0,
    explanation: 'Le décalage vers le rouge cosmologique traduit l’allongement de la longueur d’onde de la lumière reçue.',
    tags: ['astronomie', 'cosmologie', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/D%C3%A9calage_vers_le_rouge',
  },
  {
    id: 'astro-018',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quelle limite de distance marque la zone où les forces de marée peuvent disloquer un satellite ?',
    choices: ['Limite de Roche', 'Limite de Chandrasekhar', 'Rayon de Schwarzschild', 'Sphère de Hill uniquement'],
    answerIndex: 0,
    explanation: 'La limite de Roche décrit une distance critique où les forces de marée d’un corps massif peuvent rompre un satellite.',
    tags: ['astronomie', 'gravitation', 'subtheme:astronomy:solar-system'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Limite_de_Roche',
  },
  {
    id: 'astro-019',
    topicId: 'astronomy',
    difficulty: 3,
    prompt: 'Quel diagramme place les étoiles selon leur luminosité et leur température de surface ?',
    choices: ['Diagramme de Hertzsprung-Russell', 'Diagramme de Feynman', 'Diagramme de Venn', 'Diagramme de Mollweide'],
    answerIndex: 0,
    explanation: 'Le diagramme de Hertzsprung-Russell relie luminosité et température, et permet de situer les grandes familles d’étoiles.',
    tags: ['astronomie', 'etoiles', 'subtheme:astronomy:observation'],
    sourceLabel: 'Contenu original Kizz',
    learnMoreUrl: 'https://fr.wikipedia.org/wiki/Diagramme_de_Hertzsprung-Russell',
  },
];
